import { Branch } from "@/types";

export const branches: Branch[] = [
  {
    id: "br-1",
    branchId: "BR-01",
    name: "Nairobi CBD",
    city: "Nairobi",
    region: "Nairobi",
    branchManager: "Janet Muthoni",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Daniel Mwendwa",
    capacity: 12,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
  },
  {
    id: "br-2",
    branchId: "BR-02",
    name: "Eastlands",
    city: "Nairobi",
    region: "Nairobi",
    branchManager: "Paul Were",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Daniel Mwendwa",
    capacity: 9,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
  },
  {
    id: "br-3",
    branchId: "BR-03",
    name: "Westlands",
    city: "Nairobi",
    region: "Nairobi",
    branchManager: "Agnes Wangari",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Daniel Mwendwa",
    capacity: 10,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
  },
  {
    id: "br-4",
    branchId: "BR-04",
    name: "Southlands",
    city: "Nairobi",
    region: "Nairobi",
    branchManager: "Stephen Kamau",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Daniel Mwendwa",
    capacity: 8,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
  },
  {
    id: "br-5",
    branchId: "BR-05",
    name: "Mombasa",
    city: "Mombasa",
    region: "Coast",
    branchManager: "Florence Atieno",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Kevin Kiptoo",
    capacity: 11,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
  },
  {
    id: "br-6",
    branchId: "BR-06",
    name: "Kisumu",
    city: "Kisumu",
    region: "Nyanza",
    branchManager: "Michael Otieno",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Kevin Kiptoo",
    capacity: 7,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
  },
  {
    id: "br-7",
    branchId: "BR-07",
    name: "Nakuru",
    city: "Nakuru",
    region: "Rift Valley",
    branchManager: "Catherine Akinyi",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Kevin Kiptoo",
    capacity: 9,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
  },
  {
    id: "br-8",
    branchId: "BR-08",
    name: "Support Office",
    city: "Nairobi",
    region: "Nairobi",
    branchManager: "—",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "—",
    capacity: 40,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
  },
  // Expansion branches — placeholder details until the real branch
  // manager/capacity are confirmed; expansionBranch:true is what scopes
  // them into the Expansion Tracker (/expansion), not the name/id.
  {
    id: "br-9",
    branchId: "BR-09",
    name: "Kinoo",
    city: "Nairobi",
    region: "Nairobi",
    branchManager: "TBD",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Daniel Mwendwa",
    capacity: 8,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
    expansionBranch: true,
  },
  {
    id: "br-10",
    branchId: "BR-10",
    name: "G44",
    city: "Nairobi",
    region: "Nairobi",
    branchManager: "TBD",
    bmEmail: "",
    bmPhone: "",
    regionalManager: "Daniel Mwendwa",
    capacity: 8,
    active: true,
    workTrialActive: true,
    address: "",
    mapPinUrl: "",
    expansionBranch: true,
  },
];
