import { Interview } from "@/types";

export const interviews: Interview[] = [
  { id: "int-1", schedId: "SCH-001", candidateId: "cand-1", roleId: "role-1", date: "2026-06-22", time: "09:00", weekLabel: "W4 Jun 2026", month: "Jun 2026", stage: "First Interview", type: "In-person", location: "Nairobi CBD", interviewers: ["Dr. Wanjiru"], confirmed: true, reminderSent: false, attendance: "Pending", outcome: "Pending" },
  { id: "int-2", schedId: "SCH-002", candidateId: "cand-2", roleId: "role-2", date: "2026-06-21", time: "11:00", weekLabel: "W3 Jun 2026", month: "Jun 2026", stage: "First Interview", type: "Google Meet", location: "meet.google.com/penda-ta-1", interviewers: ["Brian O."], confirmed: false, reminderSent: true, attendance: "Pending", outcome: "Pending" },
  { id: "int-3", schedId: "SCH-003", candidateId: "cand-3", roleId: "role-4", date: "2026-06-23", time: "14:00", weekLabel: "W4 Jun 2026", month: "Jun 2026", stage: "First Interview", type: "In-person", location: "Mombasa", interviewers: ["Dr. Aisha"], confirmed: true, reminderSent: false, attendance: "Pending", outcome: "Pending" },
  { id: "int-4", schedId: "SCH-004", candidateId: "cand-7", roleId: "role-1", date: "2026-06-20", time: "10:00", weekLabel: "W3 Jun 2026", month: "Jun 2026", stage: "Second Interview", type: "In-person", location: "Nairobi CBD", interviewers: ["Dr. Wanjiru", "Mash"], confirmed: true, reminderSent: true, attendance: "Attended", outcome: "Pending" },
  { id: "int-5", schedId: "SCH-005", candidateId: "cand-8", roleId: "role-6", date: "2026-06-18", time: "09:30", weekLabel: "W3 Jun 2026", month: "Jun 2026", stage: "Second Interview", type: "In-person", location: "Nakuru", interviewers: ["Dr. Wanjiru"], confirmed: true, reminderSent: true, attendance: "Attended", outcome: "Pass" },
  { id: "int-6", schedId: "SCH-006", candidateId: "cand-9", roleId: "role-3", date: "2026-06-17", time: "13:00", weekLabel: "W3 Jun 2026", month: "Jun 2026", stage: "Second Interview", type: "Phone", location: "—", interviewers: ["Dr. Aisha"], confirmed: false, reminderSent: true, attendance: "No-show", outcome: "Pending" },
  { id: "int-7", schedId: "SCH-007", candidateId: "cand-10", roleId: "role-10", date: "2026-06-16", time: "15:00", weekLabel: "W3 Jun 2026", month: "Jun 2026", stage: "Panel Interview", type: "In-person", location: "Support Office", interviewers: ["Kassim A.", "Mash"], confirmed: true, reminderSent: true, attendance: "Attended", outcome: "Pass" },
  { id: "int-8", schedId: "SCH-008", candidateId: "cand-11", roleId: "role-6", date: "2026-06-19", time: "10:30", weekLabel: "W3 Jun 2026", month: "Jun 2026", stage: "Panel Interview", type: "In-person", location: "Nakuru", interviewers: ["Dr. Wanjiru", "Mash"], confirmed: true, reminderSent: true, attendance: "Attended", outcome: "Pass" },
];
