import { OpenRole } from "@/types";

export const openRoles: OpenRole[] = [
  {
    id: "role-1",
    roleId: "ROL-001",
    title: "Clinical Officer",
    segment: "IPS",
    department: "Clinical Services",
    location: "Nairobi CBD",
    branchId: "br-1",
    priority: "Critical",
    status: "Open",
    hcApproved: 2,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-05-10",
  },
  {
    id: "role-2",
    roleId: "ROL-002",
    title: "Pharm Tech",
    segment: "IPS",
    department: "Pharmacy",
    location: "Eastlands",
    branchId: "br-2",
    priority: "High",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Brian O.",
    datePosted: "2026-05-18",
  },
  {
    id: "role-3",
    roleId: "ROL-003",
    title: "Lab Technician",
    segment: "IPS",
    department: "Lab",
    location: "Westlands",
    branchId: "br-3",
    priority: "Medium",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Aisha",
    datePosted: "2026-05-22",
  },
  {
    id: "role-4",
    roleId: "ROL-004",
    title: "Dentist",
    segment: "IPS",
    department: "Dental",
    location: "Mombasa",
    branchId: "br-5",
    priority: "High",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Aisha",
    datePosted: "2026-05-02",
  },
  {
    id: "role-5",
    roleId: "ROL-005",
    title: "COHO",
    segment: "IPS",
    department: "Clinical Services",
    location: "Kisumu",
    branchId: "br-6",
    priority: "Medium",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-05-28",
  },
  {
    id: "role-6",
    roleId: "ROL-006",
    title: "Nurse",
    segment: "IPS",
    department: "Clinical Services",
    location: "Nakuru",
    branchId: "br-7",
    priority: "Critical",
    status: "Open",
    hcApproved: 2,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-04-29",
  },
  {
    id: "role-7",
    roleId: "ROL-007",
    title: "Customer Service Representative",
    segment: "IPS",
    department: "Customer Service",
    location: "Southlands",
    branchId: "br-4",
    priority: "Low",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Brian O.",
    datePosted: "2026-06-05",
  },
  {
    id: "role-8",
    roleId: "ROL-008",
    title: "People & Culture Officer",
    segment: "SO",
    department: "People & Culture",
    location: "Support Office",
    branchId: "br-8",
    priority: "High",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Fatuma A.",
    datePosted: "2026-05-15",
  },
  {
    id: "role-9",
    roleId: "ROL-009",
    title: "Finance Analyst",
    segment: "SO",
    department: "Finance",
    location: "Support Office",
    branchId: "br-8",
    priority: "Medium",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "James N.",
    datePosted: "2026-05-30",
  },
  {
    id: "role-10",
    roleId: "ROL-010",
    title: "IT Support Engineer",
    segment: "SO",
    department: "IT",
    location: "Support Office",
    branchId: "br-8",
    priority: "Critical",
    status: "Filled",
    hcApproved: 1,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Kassim A.",
    datePosted: "2026-04-10",
  },
  // Expansion branch (Kinoo / G44) roles — feeds /expansion. A mix of
  // internal fills (some linked to a backfill requisition, one not yet),
  // external hires, and a still-open role, plus the backfill roles those
  // internal moves triggered elsewhere (linked via requisitionId back to
  // the matching req-6/7/8 in requisitions.ts).
  {
    id: "role-11",
    roleId: "ROL-011",
    title: "Clinical Officer",
    segment: "IPS",
    department: "Clinical Services",
    location: "Kinoo",
    branchId: "br-9",
    priority: "Critical",
    status: "Filled",
    hcApproved: 1,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-08-01",
    internalFill: true,
    internalFillName: "Jane Wambui",
    replacementRequisitionId: "req-6", // Pending Approval — backfill not yet raised-through
  },
  {
    id: "role-12",
    roleId: "ROL-012",
    title: "Pharm Tech",
    segment: "IPS",
    department: "Pharmacy",
    location: "G44",
    branchId: "br-10",
    priority: "High",
    status: "Filled",
    hcApproved: 1,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Brian O.",
    datePosted: "2026-07-18",
    internalFill: true,
    internalFillName: "Peter Otieno",
    replacementRequisitionId: "req-7", // Converted to Open Role — see role-13
  },
  {
    id: "role-13",
    roleId: "ROL-013",
    title: "Pharm Tech",
    segment: "IPS",
    department: "Pharmacy",
    location: "Eastlands",
    branchId: "br-2",
    priority: "Medium",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Brian O.",
    datePosted: "2026-07-22",
    requisitionId: "req-7", // the backfill this Pharm Tech promotion into G44 created
  },
  {
    id: "role-14",
    roleId: "ROL-014",
    title: "COHO",
    segment: "IPS",
    department: "Clinical Services",
    location: "G44",
    branchId: "br-10",
    priority: "High",
    status: "Filled",
    hcApproved: 1,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-06-20",
    internalFill: true,
    internalFillName: "Grace Njeri",
    replacementRequisitionId: "req-8", // Converted, and role-15 below is already filled — "Backfilled"
  },
  {
    id: "role-15",
    roleId: "ROL-015",
    title: "Nurse",
    segment: "IPS",
    department: "Clinical Services",
    location: "Nakuru",
    branchId: "br-7",
    priority: "Medium",
    status: "Filled",
    hcApproved: 1,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-06-28",
    dateClosed: "2026-07-15",
    requisitionId: "req-8",
  },
  {
    id: "role-16",
    roleId: "ROL-016",
    title: "Dentist",
    segment: "IPS",
    department: "Dental",
    location: "Kinoo",
    branchId: "br-9",
    priority: "High",
    status: "Filled",
    hcApproved: 1,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Aisha",
    datePosted: "2026-08-10",
    internalFill: true,
    internalFillName: "Mercy Wanjiku",
    // No replacementRequisitionId yet — nothing's been raised to backfill
    // Mercy's old seat. Renders as "Needs replacement" until someone links one.
  },
  {
    id: "role-17",
    roleId: "ROL-017",
    title: "Nurse",
    segment: "IPS",
    department: "Clinical Services",
    location: "Kinoo",
    branchId: "br-9",
    priority: "Critical",
    status: "Open",
    hcApproved: 2,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-08-12",
  },
  {
    id: "role-18",
    roleId: "ROL-018",
    title: "Customer Service Representative",
    segment: "IPS",
    department: "Customer Service",
    location: "G44",
    branchId: "br-10",
    priority: "Medium",
    status: "Filled",
    hcApproved: 1,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Brian O.",
    datePosted: "2026-07-05",
  },
];
