import { OpenRole } from "@/types";

export const openRoles: OpenRole[] = [
  {
    id: "role-1",
    roleId: "ROL-001",
    title: "Clinical Officer",
    segment: "IPS",
    department: "Clinical",
    location: "Nairobi CBD",
    branchId: "br-1",
    priority: "Critical",
    status: "Open",
    hcApproved: 2,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-05-10",
  },
  {
    id: "role-2",
    roleId: "ROL-002",
    title: "Pharm Tech",
    segment: "IPS",
    department: "Pharmacy",
    location: "Eastlands",
    branchId: "br-2",
    priority: "High",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Brian O.",
    datePosted: "2026-05-18",
  },
  {
    id: "role-3",
    roleId: "ROL-003",
    title: "Lab Technician",
    segment: "IPS",
    department: "Lab",
    location: "Westlands",
    branchId: "br-3",
    priority: "Medium",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Aisha",
    datePosted: "2026-05-22",
  },
  {
    id: "role-4",
    roleId: "ROL-004",
    title: "Dentist",
    segment: "IPS",
    department: "Dental",
    location: "Mombasa",
    branchId: "br-5",
    priority: "High",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Aisha",
    datePosted: "2026-05-02",
  },
  {
    id: "role-5",
    roleId: "ROL-005",
    title: "COHO",
    segment: "IPS",
    department: "Clinical",
    location: "Kisumu",
    branchId: "br-6",
    priority: "Medium",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-05-28",
  },
  {
    id: "role-6",
    roleId: "ROL-006",
    title: "Nurse",
    segment: "IPS",
    department: "Clinical",
    location: "Nakuru",
    branchId: "br-7",
    priority: "Critical",
    status: "Open",
    hcApproved: 2,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Dr. Wanjiru",
    datePosted: "2026-04-29",
  },
  {
    id: "role-7",
    roleId: "ROL-007",
    title: "Customer Service Representative",
    segment: "IPS",
    department: "Customer Service",
    location: "Southlands",
    branchId: "br-4",
    priority: "Low",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Brian O.",
    datePosted: "2026-06-05",
  },
  {
    id: "role-8",
    roleId: "ROL-008",
    title: "People & Culture Officer",
    segment: "SO",
    department: "People & Culture",
    location: "Support Office",
    branchId: "br-8",
    priority: "High",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "Fatuma A.",
    datePosted: "2026-05-15",
  },
  {
    id: "role-9",
    roleId: "ROL-009",
    title: "Finance Analyst",
    segment: "SO",
    department: "Finance",
    location: "Support Office",
    branchId: "br-8",
    priority: "Medium",
    status: "Open",
    hcApproved: 1,
    hcFilled: 0,
    recruiter: "Samwel K.",
    hiringManager: "James N.",
    datePosted: "2026-05-30",
  },
  {
    id: "role-10",
    roleId: "ROL-010",
    title: "IT Support Engineer",
    segment: "SO",
    department: "IT",
    location: "Support Office",
    branchId: "br-8",
    priority: "Critical",
    status: "Filled",
    hcApproved: 1,
    hcFilled: 1,
    recruiter: "Samwel K.",
    hiringManager: "Kassim A.",
    datePosted: "2026-04-10",
  },
];
