import { ReferenceCheck } from "@/types";

export const referenceChecks: ReferenceCheck[] = [
  {
    id: "ref-1",
    refId: "REF-001",
    candidateId: "cand-16",
    referees: [
      {
        name: "Dr. Omondi Achieng",
        email: "omondi.achieng@example.com",
        phone: "+254722000001",
        emailSent: true,
        smsSent: true,
        responded: true,
        respondedAt: "2026-06-17T10:00:00",
      },
      {
        name: "Nancy Wairimu",
        email: "nancy.wairimu@example.com",
        phone: "+254722000002",
        emailSent: true,
        smsSent: true,
        responded: false,
      },
    ],
    outcome: "Pending",
    driveFolderUrl: "https://drive.google.com/drive/folders/june-2026-felix-kiprotich",
    createdAt: "2026-06-16",
    source: "TA Added",
    status: "1 Referee In",
    verifiedAt: "2026-06-16",
    verifiedBy: "TA Team",
    initiatedAt: "2026-06-16",
    aiInsights: null,
  },
  {
    id: "ref-2",
    refId: "REF-002",
    candidateId: "cand-17",
    referees: [
      {
        name: "Dr. Hassan Ali",
        email: "hassan.ali@example.com",
        phone: "+254722000003",
        emailSent: true,
        smsSent: true,
        responded: false,
      },
      {
        name: "Beatrice Kanini",
        email: "beatrice.kanini@example.com",
        phone: "+254722000004",
        emailSent: true,
        smsSent: true,
        responded: false,
      },
    ],
    outcome: "Pending",
    driveFolderUrl: "https://drive.google.com/drive/folders/june-2026-naomi-akinyi",
    createdAt: "2026-06-17",
    source: "TA Added",
    status: "Awaiting Responses",
    verifiedAt: "2026-06-17",
    verifiedBy: "TA Team",
    initiatedAt: "2026-06-17",
    aiInsights: null,
  },
  {
    id: "ref-3",
    refId: "REF-003",
    candidateId: "cand-18",
    referees: [
      {
        name: "Susan Mbithe",
        email: "susan.mbithe@example.com",
        phone: "+254722000005",
        emailSent: true,
        smsSent: true,
        responded: true,
        respondedAt: "2026-06-09T08:00:00",
      },
      {
        name: "Tom Kiplangat",
        email: "tom.kiplangat@example.com",
        phone: "+254722000006",
        emailSent: true,
        smsSent: true,
        responded: true,
        respondedAt: "2026-06-09T14:00:00",
      },
    ],
    outcome: "Positive",
    driveFolderUrl: "https://drive.google.com/drive/folders/may-2026-dennis-mwangi",
    createdAt: "2026-06-08",
    source: "TA Added",
    status: "Ready for Offer",
    verifiedAt: "2026-06-08",
    verifiedBy: "TA Team",
    initiatedAt: "2026-06-08",
    aiInsights: {
      overallStatus: "Strong Recommend",
      summary:
        "Both referees independently described Dennis as technically strong and highly reliable, with consistent praise for his calm handling of high-pressure situations and collaborative style with the wider team.",
      recommendationScore: 5,
      overallScore: 4.5,
      confidenceScore: 92,
      keyStrengths: [
        "Both referees cited specific examples of Dennis staying composed and effective during high-patient-volume shifts.",
        "Susan noted he proactively mentored newer staff without being asked.",
      ],
      areasOfConcern: ["Tom mentioned Dennis can be slow to delegate when under time pressure, preferring to do it himself."],
      consistencyNotes:
        "Strong agreement between both referees on technical skill and reliability; the only divergence is Tom's delegation note, which Susan didn't raise.",
      suggestedFollowUps: ["Ask Dennis directly how he approaches delegating tasks when a shift gets busy."],
      refereeTakeaways: [
        "Susan: Consistently dependable and a natural mentor to newer staff.",
        "Tom: Technically excellent, though could delegate more under pressure.",
      ],
      generatedAt: "2026-06-10T09:15:00.000Z",
    },
  },
];
