import { ReferenceCheck } from "@/types";

export const referenceChecks: ReferenceCheck[] = [
  {
    id: "ref-1",
    refId: "REF-001",
    candidateId: "cand-16",
    referee1: {
      name: "Dr. Omondi Achieng",
      email: "omondi.achieng@example.com",
      phone: "+254722000001",
      emailSent: true,
      smsSent: true,
      responded: true,
      respondedAt: "2026-06-17T10:00:00",
    },
    referee2: {
      name: "Nancy Wairimu",
      email: "nancy.wairimu@example.com",
      phone: "+254722000002",
      emailSent: true,
      smsSent: true,
      responded: false,
    },
    outcome: "Pending",
    driveFolderUrl: "https://drive.google.com/drive/folders/june-2026-felix-kiprotich",
    createdAt: "2026-06-16",
  },
  {
    id: "ref-2",
    refId: "REF-002",
    candidateId: "cand-17",
    referee1: {
      name: "Dr. Hassan Ali",
      email: "hassan.ali@example.com",
      phone: "+254722000003",
      emailSent: true,
      smsSent: true,
      responded: false,
    },
    referee2: {
      name: "Beatrice Kanini",
      email: "beatrice.kanini@example.com",
      phone: "+254722000004",
      emailSent: true,
      smsSent: true,
      responded: false,
    },
    outcome: "Pending",
    driveFolderUrl: "https://drive.google.com/drive/folders/june-2026-naomi-akinyi",
    createdAt: "2026-06-17",
  },
  {
    id: "ref-3",
    refId: "REF-003",
    candidateId: "cand-18",
    referee1: {
      name: "Susan Mbithe",
      email: "susan.mbithe@example.com",
      phone: "+254722000005",
      emailSent: true,
      smsSent: true,
      responded: true,
      respondedAt: "2026-06-09T08:00:00",
    },
    referee2: {
      name: "Tom Kiplangat",
      email: "tom.kiplangat@example.com",
      phone: "+254722000006",
      emailSent: true,
      smsSent: true,
      responded: true,
      respondedAt: "2026-06-09T14:00:00",
    },
    outcome: "Positive",
    driveFolderUrl: "https://drive.google.com/drive/folders/may-2026-dennis-mwangi",
    createdAt: "2026-06-08",
  },
];
