import { Requisition } from "@/types";

export const requisitions: Requisition[] = [
  {
    id: "req-1",
    reqId: "REQ-001",
    type: "IPS Gap",
    roleTitle: "Clinical Officer",
    department: "Clinical",
    segment: "IPS",
    gapReason: "Promotion",
    branchId: "br-1",
    headcount: 1,
    justification: "Incumbent promoted to Branch Manager, backfill needed to maintain patient coverage.",
    salaryRangeMin: 65000,
    salaryRangeMax: 85000,
    urgency: "Critical",
    jdAttached: true,
    status: "Pending Approval",
    approverChain: ["Dr. Wanjiru", "Mash", "Mwihaki"],
    currentApproverIndex: 0,
    submittedBy: "Samwel K.",
    submittedAt: "2026-06-15T09:00:00",
    expectedStartDate: "2026-07-15",
  },
  {
    id: "req-2",
    reqId: "REQ-002",
    type: "SO New Role",
    roleTitle: "Talent Acquisition Coordinator",
    department: "People & Culture",
    segment: "SO",
    branchId: "br-8",
    headcount: 1,
    justification: "Hiring volume has outpaced current TA team capacity across both segments.",
    salaryRangeMin: 55000,
    salaryRangeMax: 70000,
    urgency: "High",
    jdAttached: true,
    status: "Approved",
    approverChain: ["Mash", "Mwihaki"],
    currentApproverIndex: 2,
    submittedBy: "Mash",
    submittedAt: "2026-06-02T10:30:00",
    expectedStartDate: "2026-07-01",
  },
  {
    id: "req-3",
    reqId: "REQ-003",
    type: "IPS Gap",
    roleTitle: "Pharm Tech",
    department: "Pharmacy",
    segment: "IPS",
    gapReason: "Voluntary Resignation",
    branchId: "br-2",
    headcount: 1,
    justification: "Pharm Tech resigned with two weeks notice, branch operating below minimum staffing.",
    salaryRangeMin: 45000,
    salaryRangeMax: 55000,
    urgency: "High",
    jdAttached: true,
    status: "Converted to Open Role",
    approverChain: ["Brian O.", "Mash"],
    currentApproverIndex: 2,
    submittedBy: "Samwel K.",
    submittedAt: "2026-05-16T08:15:00",
    expectedStartDate: "2026-06-15",
  },
  {
    id: "req-4",
    reqId: "REQ-004",
    type: "SO Replacement",
    roleTitle: "Payroll Officer",
    department: "Finance",
    segment: "SO",
    gapReason: "Termination",
    branchId: "br-8",
    headcount: 1,
    justification: "Replacement for terminated payroll officer; role is business-critical for monthly payroll runs.",
    salaryRangeMin: 60000,
    salaryRangeMax: 75000,
    urgency: "Critical",
    jdAttached: false,
    status: "Rejected",
    approverChain: ["James N.", "Mwihaki"],
    currentApproverIndex: 1,
    submittedBy: "James N.",
    submittedAt: "2026-06-10T14:00:00",
    context: "Rejected pending updated budget approval from Finance committee.",
  },
  {
    id: "req-5",
    reqId: "REQ-005",
    type: "IPS Gap",
    roleTitle: "Nurse",
    department: "Clinical",
    segment: "IPS",
    gapReason: "New Addition",
    branchId: "br-7",
    headcount: 1,
    justification: "Patient volume growth at Nakuru branch requires an additional nurse on the floor.",
    salaryRangeMin: 50000,
    salaryRangeMax: 60000,
    urgency: "Medium",
    jdAttached: true,
    status: "Pending Approval",
    approverChain: ["Dr. Wanjiru", "Mash", "Mwihaki"],
    currentApproverIndex: 1,
    submittedBy: "Samwel K.",
    submittedAt: "2026-06-18T11:20:00",
    expectedStartDate: "2026-08-01",
  },
];
