import { WorkTrial } from "@/types";

export const workTrials: WorkTrial[] = [
  {
    id: "wt-1",
    wtId: "WT-001",
    candidateId: "cand-12",
    branchId: "br-1",
    date: "2026-06-21",
    supervisor: "Dr. Wanjiru",
    arrivalMarked: null,
    scoreTechnical: null,
    scorePatient: null,
    scoreSafety: null,
    scoreCulture: null,
    total: null,
    passFail: "Pending",
    formSubmittedAt: null,
    reminder12hSent: false,
    escalation24hSent: false,
  },
  {
    id: "wt-2",
    wtId: "WT-002",
    candidateId: "cand-13",
    branchId: "br-7",
    date: "2026-06-19",
    supervisor: "Dr. Wanjiru",
    arrivalMarked: true,
    scoreTechnical: null,
    scorePatient: null,
    scoreSafety: null,
    scoreCulture: null,
    total: null,
    passFail: "Pending",
    formSubmittedAt: null,
    reminder12hSent: true,
    escalation24hSent: false,
  },
  {
    id: "wt-3",
    wtId: "WT-003",
    candidateId: "cand-14",
    branchId: "br-6",
    date: "2026-06-15",
    supervisor: "Dr. Wanjiru",
    arrivalMarked: true,
    scoreTechnical: 85,
    scorePatient: 80,
    scoreSafety: 90,
    scoreCulture: 75,
    total: 83.5,
    passFail: "Pass",
    formSubmittedAt: "2026-06-15T17:30:00",
    reminder12hSent: false,
    escalation24hSent: false,
  },
  {
    id: "wt-4",
    wtId: "WT-004",
    candidateId: "cand-15",
    branchId: "br-4",
    date: "2026-06-14",
    supervisor: "Brian O.",
    arrivalMarked: true,
    scoreTechnical: 60,
    scorePatient: 55,
    scoreSafety: 70,
    scoreCulture: 50,
    total: 59.5,
    passFail: "Fail",
    formSubmittedAt: "2026-06-15T09:10:00",
    reminder12hSent: true,
    escalation24hSent: true,
  },
];
