// TypeScript mirror of scripts/lib/airtable-schema.js's `F` constant and
// table names. Kept in sync by hand — both files describe the same 11
// Airtable tables, one for the setup script (plain CommonJS) and one for
// the app's runtime mappers (TypeScript, used by API routes).

export const TABLE_NAMES = {
  Branches: "Branches",
  Requisitions: "Requisitions",
  OpenRoles: "Open Roles",
  Candidates: "Candidates",
  Interviews: "Interviews",
  WorkTrials: "Work Trials",
  ReferenceChecks: "Reference Checks",
  Offers: "Offers",
  NewEmployees: "New Employees",
  Relievers: "Relievers",
  Locums: "Locums",
} as const;

export const F = {
  Branches: {
    BRANCH_ID: "Branch ID",
    NAME: "Name",
    CITY: "City",
    REGION: "Region",
    BRANCH_MANAGER: "Branch Manager",
    REGIONAL_MANAGER: "Regional Manager",
    CAPACITY: "Capacity",
    ACTIVE: "Active",
  },
  Requisitions: {
    REQ_ID: "Req ID",
    TYPE: "Type",
    ROLE_TITLE: "Role Title",
    DEPARTMENT: "Department",
    SEGMENT: "Segment",
    GAP_REASON: "Gap Reason",
    REASON_TYPE: "Reason Type",
    BRANCH: "Branch",
    EMPLOYMENT_TYPE: "Employment Type",
    LEVEL: "Level",
    HEADCOUNT: "Headcount",
    JUSTIFICATION: "Justification",
    SALARY_MIN: "Salary Range Min",
    SALARY_MAX: "Salary Range Max",
    URGENCY: "Urgency",
    JD_ATTACHED: "JD Attached",
    JD_URL: "JD URL",
    STATUS: "Status",
    APPROVER_CHAIN: "Approver Chain",
    CURRENT_APPROVER_INDEX: "Current Approver Index",
    SUBMITTED_BY: "Submitted By",
    SUBMITTED_AT: "Submitted At",
    EXPECTED_START_DATE: "Expected Start Date",
    CONTEXT: "Context",
  },
  OpenRoles: {
    ROLE_ID: "Role ID",
    TITLE: "Title",
    SEGMENT: "Segment",
    DEPARTMENT: "Department",
    LOCATION: "Location",
    BRANCH: "Branch",
    PRIORITY: "Priority",
    STATUS: "Status",
    HC_APPROVED: "HC Approved",
    HC_FILLED: "HC Filled",
    RECRUITER: "Recruiter",
    HIRING_MANAGER: "Hiring Manager",
    DATE_POSTED: "Date Posted",
    DATE_CLOSED: "Date Closed",
    EMPLOYMENT_TYPE: "Employment Type",
    NOTES: "Notes",
    REQUISITION: "Requisition",
  },
  Candidates: {
    CAND_ID: "Cand ID",
    NAME: "Name",
    PHONE: "Phone",
    EMAIL: "Email",
    ROLE: "Role",
    STAGE: "Stage",
    SOURCE: "Source",
    GENDER: "Gender",
    EMPLOYMENT_TYPE: "Employment Type",
    REFEREE1_NAME: "Referee 1 Name",
    REFEREE1_EMAIL: "Referee 1 Email",
    REFEREE1_PHONE: "Referee 1 Phone",
    REFEREE2_NAME: "Referee 2 Name",
    REFEREE2_EMAIL: "Referee 2 Email",
    REFEREE2_PHONE: "Referee 2 Phone",
    WORK_TRIAL_STATUS: "Work Trial Status",
    REF_CHECK_STATUS: "Ref Check Status",
    OFFER_STATUS: "Offer Status",
    JOINED: "Joined",
    STAGE_ENTERED_AT: "Stage Entered At",
    CREATED_AT: "Created At",
  },
  Interviews: {
    SCHED_ID: "Sched ID",
    CANDIDATE: "Candidate",
    ROLE: "Role",
    DATE: "Date",
    TIME: "Time",
    WEEK_LABEL: "Week Label",
    MONTH: "Month",
    STAGE: "Stage",
    TYPE: "Type",
    LOCATION: "Location",
    INTERVIEWERS: "Interviewers",
    CONFIRMED: "Confirmed",
    REMINDER_SENT: "Reminder Sent",
    ATTENDANCE: "Attendance",
    OUTCOME: "Outcome",
    NOTES: "Notes",
  },
  WorkTrials: {
    WT_ID: "WT ID",
    CANDIDATE: "Candidate",
    BRANCH: "Branch",
    DATE: "Date",
    SUPERVISOR: "Supervisor",
    ARRIVAL_MARKED: "Arrival Marked",
    SCORE_TECHNICAL: "Score Technical",
    SCORE_PATIENT: "Score Patient",
    SCORE_SAFETY: "Score Safety",
    SCORE_CULTURE: "Score Culture",
    TOTAL: "Total",
    PASS_FAIL: "Pass/Fail",
    FORM_SUBMITTED_AT: "Form Submitted At",
    REMINDER_12H_SENT: "Reminder 12h Sent",
    ESCALATION_24H_SENT: "Escalation 24h Sent",
  },
  ReferenceChecks: {
    REF_ID: "Ref ID",
    CANDIDATE: "Candidate",
    REFEREE1_NAME: "Referee 1 Name",
    REFEREE1_EMAIL: "Referee 1 Email",
    REFEREE1_PHONE: "Referee 1 Phone",
    REFEREE1_EMAIL_SENT: "Referee 1 Email Sent",
    REFEREE1_SMS_SENT: "Referee 1 SMS Sent",
    REFEREE1_RESPONDED: "Referee 1 Responded",
    REFEREE1_RESPONDED_AT: "Referee 1 Responded At",
    REFEREE1_RELATIONSHIP: "Referee 1 Relationship",
    REFEREE1_DURATION_KNOWN: "Referee 1 Duration Known",
    REFEREE1_TECH_SCORE: "Referee 1 Tech Score",
    REFEREE1_RELIABILITY_SCORE: "Referee 1 Reliability Score",
    REFEREE1_TEAMWORK_SCORE: "Referee 1 Teamwork Score",
    REFEREE1_WOULD_REHIRE: "Referee 1 Would Rehire",
    REFEREE1_STRENGTH_EXAMPLE: "Referee 1 Strength Example",
    REFEREE1_DEVELOPMENT_AREAS: "Referee 1 Development Areas",
    REFEREE1_NOTES: "Referee 1 Notes",
    REFEREE2_NAME: "Referee 2 Name",
    REFEREE2_EMAIL: "Referee 2 Email",
    REFEREE2_PHONE: "Referee 2 Phone",
    REFEREE2_EMAIL_SENT: "Referee 2 Email Sent",
    REFEREE2_SMS_SENT: "Referee 2 SMS Sent",
    REFEREE2_RESPONDED: "Referee 2 Responded",
    REFEREE2_RESPONDED_AT: "Referee 2 Responded At",
    REFEREE2_RELATIONSHIP: "Referee 2 Relationship",
    REFEREE2_DURATION_KNOWN: "Referee 2 Duration Known",
    REFEREE2_TECH_SCORE: "Referee 2 Tech Score",
    REFEREE2_RELIABILITY_SCORE: "Referee 2 Reliability Score",
    REFEREE2_TEAMWORK_SCORE: "Referee 2 Teamwork Score",
    REFEREE2_WOULD_REHIRE: "Referee 2 Would Rehire",
    REFEREE2_STRENGTH_EXAMPLE: "Referee 2 Strength Example",
    REFEREE2_DEVELOPMENT_AREAS: "Referee 2 Development Areas",
    REFEREE2_NOTES: "Referee 2 Notes",
    OUTCOME: "Outcome",
    DRIVE_FOLDER_URL: "Drive Folder URL",
    CREATED_AT: "Created At",
  },
  Offers: {
    OFFER_ID: "Offer ID",
    CANDIDATE: "Candidate",
    OFFERED_SALARY: "Offered Salary",
    BUDGETED_SALARY: "Budgeted Salary",
    DATE_SENT: "Date Sent",
    DEADLINE: "Deadline",
    OUTCOME: "Outcome",
    COUNTER_OFFER_AMOUNT: "Counter Offer Amount",
    FINAL_ACCEPTED_SALARY: "Final Accepted Salary",
    START_DATE: "Start Date",
    JOINED: "Joined",
    DROP_REASON: "Drop Reason",
  },
  NewEmployees: {
    EMPLOYEE_ID: "Employee ID",
    CANDIDATE: "Candidate",
    NAME: "Name",
    ROLE: "Role",
    DEPARTMENT: "Department",
    BRANCH: "Branch",
    START_DATE: "Start Date",
    EMPLOYMENT_TYPE: "Employment Type",
    CONTRACT_END: "Contract End",
  },
  Relievers: {
    RELIEVER_ID: "Reliever ID",
    NAME: "Name",
    ROLE: "Role",
    BRANCHES_COVERED: "Branches Covered",
    AVAILABILITY_DATES: "Availability Dates",
    STATUS: "Status",
    PHONE: "Phone",
    NOTES: "Notes",
  },
  Locums: {
    LOCUM_ID: "Locum ID",
    NAME: "Name",
    SPECIALITY: "Speciality",
    BRANCHES_COVERED: "Branches Covered",
    DAILY_RATE: "Daily Rate",
    LICENSE_NUMBER: "License Number",
    AVAILABILITY: "Availability",
    LAST_DEPLOYED: "Last Deployed",
  },
} as const;
