// Single source of truth for the 11 Airtable tables that mirror src/types.ts.
// Both build-airtable-schema.js (creates tables/fields) and seed-airtable.js
// (writes records) import the field-name constants from here so the two
// scripts can never drift out of sync with each other.

const dateOpts = { dateFormat: { name: "iso", format: "YYYY-MM-DD" } };
const checkboxOpts = { icon: "check", color: "greenBright" };
const currencyOpts = { symbol: "KES ", precision: 0 };
const intOpts = { precision: 0 };
const scoreOpts = { precision: 1 };

// Mirrors src/lib/mock-data/clusters.ts. Duplicated here (rather than
// imported) because this script runs as plain CommonJS outside the Next.js
// TS pipeline. Airtable inserts use typecast: true, so any reliever/locum
// branch not listed below is still added automatically during seeding.
const RELIEVER_CADRES = [
  "Clinical Coordinator",
  "Clinical Officer",
  "Pharm Tech",
  "Lab Technician",
  "Nurse",
  "Sonographer",
];
const COVERAGE_ZONES = ["Eastleigh", "Waiyaki Way", "Utawala", "Thika Road", "Langata", "Kitengela"];
const ALL_BRANCHES = [
  "Umoja 1", "Umoja 2", "Pipeline", "Tassia", "Embakasi",
  "Kangemi", "Kawangware", "Kimathi",
  "Shooters", "Benedicata", "Kariobangi South",
  "Kahawa West", "Zimmerman", "Githurai 45", "Sunton", "Luckysummer",
  "Langata", "Kitengela",
];

function choices(names) {
  return { choices: names.map((name) => ({ name })) };
}

const F = {
  Branches: {
    BRANCH_ID: "Branch ID",
    NAME: "Name",
    CITY: "City",
    REGION: "Region",
    BRANCH_MANAGER: "Branch Manager",
    REGIONAL_MANAGER: "Regional Manager",
    CAPACITY: "Capacity",
    ACTIVE: "Active",
  },
  Requisitions: {
    REQ_ID: "Req ID",
    TYPE: "Type",
    ROLE_TITLE: "Role Title",
    DEPARTMENT: "Department",
    SEGMENT: "Segment",
    GAP_REASON: "Gap Reason",
    REASON_TYPE: "Reason Type",
    BRANCH: "Branch",
    EMPLOYMENT_TYPE: "Employment Type",
    LEVEL: "Level",
    HEADCOUNT: "Headcount",
    JUSTIFICATION: "Justification",
    SALARY_MIN: "Salary Range Min",
    SALARY_MAX: "Salary Range Max",
    URGENCY: "Urgency",
    JD_ATTACHED: "JD Attached",
    JD_URL: "JD URL",
    STATUS: "Status",
    APPROVER_CHAIN: "Approver Chain",
    CURRENT_APPROVER_INDEX: "Current Approver Index",
    SUBMITTED_BY: "Submitted By",
    SUBMITTED_AT: "Submitted At",
    EXPECTED_START_DATE: "Expected Start Date",
    CONTEXT: "Context",
    SUBMITTER_NAME: "Submitter Name",
    SUBMITTER_EMAIL: "Submitter Email",
    SUBMITTER_ROLE: "Submitter Role",
    SOURCE: "Source",
    BUDGET_EVALUATION_CONFIRMED: "Budget Evaluation Confirmed",
  },
  OpenRoles: {
    ROLE_ID: "Role ID",
    TITLE: "Title",
    SEGMENT: "Segment",
    DEPARTMENT: "Department",
    LOCATION: "Location",
    BRANCH: "Branch",
    PRIORITY: "Priority",
    STATUS: "Status",
    HC_APPROVED: "HC Approved",
    HC_FILLED: "HC Filled",
    RECRUITER: "Recruiter",
    HIRING_MANAGER: "Hiring Manager",
    DATE_POSTED: "Date Posted",
    DATE_CLOSED: "Date Closed",
    EMPLOYMENT_TYPE: "Employment Type",
    NOTES: "Notes",
    REQUISITION: "Requisition",
    REQ_SUBMITTER_NAME: "Requisition Submitter Name",
    REQ_SUBMITTER_EMAIL: "Requisition Submitter Email",
  },
  Candidates: {
    CAND_ID: "Cand ID",
    NAME: "Name",
    PHONE: "Phone",
    EMAIL: "Email",
    ROLE: "Role",
    STAGE: "Stage",
    SOURCE: "Source",
    GENDER: "Gender",
    EMPLOYMENT_TYPE: "Employment Type",
    REFEREE1_NAME: "Referee 1 Name",
    REFEREE1_EMAIL: "Referee 1 Email",
    REFEREE1_PHONE: "Referee 1 Phone",
    REFEREE2_NAME: "Referee 2 Name",
    REFEREE2_EMAIL: "Referee 2 Email",
    REFEREE2_PHONE: "Referee 2 Phone",
    WORK_TRIAL_STATUS: "Work Trial Status",
    REF_CHECK_STATUS: "Ref Check Status",
    OFFER_STATUS: "Offer Status",
    JOINED: "Joined",
    STAGE_ENTERED_AT: "Stage Entered At",
    CREATED_AT: "Created At",
  },
  Interviews: {
    SCHED_ID: "Sched ID",
    CANDIDATE: "Candidate",
    ROLE: "Role",
    DATE: "Date",
    TIME: "Time",
    WEEK_LABEL: "Week Label",
    MONTH: "Month",
    STAGE: "Stage",
    TYPE: "Type",
    LOCATION: "Location",
    INTERVIEWERS: "Interviewers",
    CONFIRMED: "Confirmed",
    REMINDER_SENT: "Reminder Sent",
    ATTENDANCE: "Attendance",
    OUTCOME: "Outcome",
    NOTES: "Notes",
  },
  WorkTrials: {
    WT_ID: "WT ID",
    CANDIDATE: "Candidate",
    BRANCH: "Branch",
    DATE: "Date",
    SUPERVISOR: "Supervisor",
    ARRIVAL_MARKED: "Arrival Marked",
    SCORE_TECHNICAL: "Score Technical",
    SCORE_PATIENT: "Score Patient",
    SCORE_SAFETY: "Score Safety",
    SCORE_CULTURE: "Score Culture",
    TOTAL: "Total",
    PASS_FAIL: "Pass/Fail",
    FORM_SUBMITTED_AT: "Form Submitted At",
    REMINDER_12H_SENT: "Reminder 12h Sent",
    ESCALATION_24H_SENT: "Escalation 24h Sent",
  },
  ReferenceChecks: {
    REF_ID: "Ref ID",
    CANDIDATE: "Candidate",
    REFEREE1_NAME: "Referee 1 Name",
    REFEREE1_EMAIL: "Referee 1 Email",
    REFEREE1_PHONE: "Referee 1 Phone",
    REFEREE1_EMAIL_SENT: "Referee 1 Email Sent",
    REFEREE1_SMS_SENT: "Referee 1 SMS Sent",
    REFEREE1_RESPONDED: "Referee 1 Responded",
    REFEREE1_RESPONDED_AT: "Referee 1 Responded At",
    REFEREE1_RELATIONSHIP: "Referee 1 Relationship",
    REFEREE1_DURATION_KNOWN: "Referee 1 Duration Known",
    REFEREE1_TECH_SCORE: "Referee 1 Tech Score",
    REFEREE1_RELIABILITY_SCORE: "Referee 1 Reliability Score",
    REFEREE1_TEAMWORK_SCORE: "Referee 1 Teamwork Score",
    REFEREE1_WOULD_REHIRE: "Referee 1 Would Rehire",
    REFEREE1_STRENGTH_EXAMPLE: "Referee 1 Strength Example",
    REFEREE1_DEVELOPMENT_AREAS: "Referee 1 Development Areas",
    REFEREE1_NOTES: "Referee 1 Notes",
    REFEREE2_NAME: "Referee 2 Name",
    REFEREE2_EMAIL: "Referee 2 Email",
    REFEREE2_PHONE: "Referee 2 Phone",
    REFEREE2_EMAIL_SENT: "Referee 2 Email Sent",
    REFEREE2_SMS_SENT: "Referee 2 SMS Sent",
    REFEREE2_RESPONDED: "Referee 2 Responded",
    REFEREE2_RESPONDED_AT: "Referee 2 Responded At",
    REFEREE2_RELATIONSHIP: "Referee 2 Relationship",
    REFEREE2_DURATION_KNOWN: "Referee 2 Duration Known",
    REFEREE2_TECH_SCORE: "Referee 2 Tech Score",
    REFEREE2_RELIABILITY_SCORE: "Referee 2 Reliability Score",
    REFEREE2_TEAMWORK_SCORE: "Referee 2 Teamwork Score",
    REFEREE2_WOULD_REHIRE: "Referee 2 Would Rehire",
    REFEREE2_STRENGTH_EXAMPLE: "Referee 2 Strength Example",
    REFEREE2_DEVELOPMENT_AREAS: "Referee 2 Development Areas",
    REFEREE2_NOTES: "Referee 2 Notes",
    OUTCOME: "Outcome",
    DRIVE_FOLDER_URL: "Drive Folder URL",
    CREATED_AT: "Created At",
  },
  Offers: {
    OFFER_ID: "Offer ID",
    CANDIDATE: "Candidate",
    OFFERED_SALARY: "Offered Salary",
    BUDGETED_SALARY: "Budgeted Salary",
    DATE_SENT: "Date Sent",
    DEADLINE: "Deadline",
    OUTCOME: "Outcome",
    COUNTER_OFFER_AMOUNT: "Counter Offer Amount",
    FINAL_ACCEPTED_SALARY: "Final Accepted Salary",
    START_DATE: "Start Date",
    JOINED: "Joined",
    DROP_REASON: "Drop Reason",
  },
  NewEmployees: {
    EMPLOYEE_ID: "Employee ID",
    CANDIDATE: "Candidate",
    NAME: "Name",
    ROLE: "Role",
    DEPARTMENT: "Department",
    BRANCH: "Branch",
    START_DATE: "Start Date",
    EMPLOYMENT_TYPE: "Employment Type",
    CONTRACT_END: "Contract End",
    CONFIRMATION_6MO: "Confirmation 6mo",
    CONFIRMATION_6MO_AT: "Confirmation 6mo At",
    REQ_SUBMITTER_NAME: "Requisition Submitter Name",
    REQ_SUBMITTER_EMAIL: "Requisition Submitter Email",
  },
  Relievers: {
    RELIEVER_ID: "Reliever ID",
    NAME: "Name",
    ROLE: "Role",
    BRANCHES_COVERED: "Branches Covered",
    AVAILABILITY_DATES: "Availability Dates",
    STATUS: "Status",
    PHONE: "Phone",
    NOTES: "Notes",
  },
  Locums: {
    LOCUM_ID: "Locum ID",
    NAME: "Name",
    SPECIALITY: "Speciality",
    BRANCHES_COVERED: "Branches Covered",
    DAILY_RATE: "Daily Rate",
    LICENSE_NUMBER: "License Number",
    AVAILABILITY: "Availability",
    LAST_DEPLOYED: "Last Deployed",
  },
};

// Order matters: every multipleRecordLinks field must point at a table that
// was already created earlier in this array.
const TABLES = [
  {
    name: "Branches",
    fields: [
      { name: F.Branches.BRANCH_ID, type: "singleLineText" },
      { name: F.Branches.NAME, type: "singleLineText" },
      { name: F.Branches.CITY, type: "singleLineText" },
      { name: F.Branches.REGION, type: "singleLineText" },
      { name: F.Branches.BRANCH_MANAGER, type: "singleLineText" },
      { name: F.Branches.REGIONAL_MANAGER, type: "singleLineText" },
      { name: F.Branches.CAPACITY, type: "number", options: intOpts },
      { name: F.Branches.ACTIVE, type: "checkbox", options: checkboxOpts },
    ],
  },
  {
    name: "Requisitions",
    fields: [
      { name: F.Requisitions.REQ_ID, type: "singleLineText" },
      { name: F.Requisitions.TYPE, type: "singleSelect", options: choices(["SO New Role", "SO Replacement", "IPS Gap"]) },
      { name: F.Requisitions.ROLE_TITLE, type: "singleLineText" },
      { name: F.Requisitions.DEPARTMENT, type: "singleLineText" },
      { name: F.Requisitions.SEGMENT, type: "singleSelect", options: choices(["IPS", "SO"]) },
      {
        name: F.Requisitions.GAP_REASON,
        type: "singleSelect",
        options: choices(["Transfer", "Promotion", "Voluntary Resignation", "Termination", "New Addition"]),
      },
      {
        name: F.Requisitions.REASON_TYPE,
        type: "singleSelect",
        options: choices(["Resignation", "Termination", "Internal Promotion", "Retirement", "Contract End", "Other"]),
      },
      { name: F.Requisitions.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      {
        name: F.Requisitions.EMPLOYMENT_TYPE,
        type: "singleSelect",
        options: choices(["Full-time", "Part-time", "Contract", "Reliever", "Locum"]),
      },
      {
        name: F.Requisitions.LEVEL,
        type: "singleSelect",
        options: choices(["Entry", "Junior", "Mid", "Senior", "Lead", "Manager", "Senior Manager", "Head/Director"]),
      },
      { name: F.Requisitions.HEADCOUNT, type: "number", options: intOpts },
      { name: F.Requisitions.JUSTIFICATION, type: "multilineText" },
      { name: F.Requisitions.SALARY_MIN, type: "currency", options: currencyOpts },
      { name: F.Requisitions.SALARY_MAX, type: "currency", options: currencyOpts },
      { name: F.Requisitions.URGENCY, type: "singleSelect", options: choices(["Critical", "High", "Medium", "Low"]) },
      { name: F.Requisitions.JD_ATTACHED, type: "checkbox", options: checkboxOpts },
      { name: F.Requisitions.JD_URL, type: "url" },
      {
        name: F.Requisitions.STATUS,
        type: "singleSelect",
        options: choices(["Pending Approval", "Approved", "Rejected", "Converted to Open Role"]),
      },
      { name: F.Requisitions.APPROVER_CHAIN, type: "multilineText" },
      { name: F.Requisitions.CURRENT_APPROVER_INDEX, type: "number", options: intOpts },
      { name: F.Requisitions.SUBMITTED_BY, type: "singleLineText" },
      { name: F.Requisitions.SUBMITTED_AT, type: "date", options: dateOpts },
      { name: F.Requisitions.EXPECTED_START_DATE, type: "date", options: dateOpts },
      { name: F.Requisitions.CONTEXT, type: "multilineText" },
      { name: F.Requisitions.SUBMITTER_NAME, type: "singleLineText" },
      { name: F.Requisitions.SUBMITTER_EMAIL, type: "email" },
      { name: F.Requisitions.SUBMITTER_ROLE, type: "singleLineText" },
      { name: F.Requisitions.SOURCE, type: "singleSelect", options: choices(["internal", "public-link"]) },
      { name: F.Requisitions.BUDGET_EVALUATION_CONFIRMED, type: "checkbox", options: checkboxOpts },
    ],
  },
  {
    name: "Open Roles",
    fields: [
      { name: F.OpenRoles.ROLE_ID, type: "singleLineText" },
      { name: F.OpenRoles.TITLE, type: "singleLineText" },
      { name: F.OpenRoles.SEGMENT, type: "singleSelect", options: choices(["IPS", "SO"]) },
      { name: F.OpenRoles.DEPARTMENT, type: "singleLineText" },
      { name: F.OpenRoles.LOCATION, type: "singleLineText" },
      { name: F.OpenRoles.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      { name: F.OpenRoles.PRIORITY, type: "singleSelect", options: choices(["Critical", "High", "Medium", "Low"]) },
      { name: F.OpenRoles.STATUS, type: "singleSelect", options: choices(["Open", "Allocated", "Filled", "On Hold", "Cancelled"]) },
      { name: F.OpenRoles.HC_APPROVED, type: "number", options: intOpts },
      { name: F.OpenRoles.HC_FILLED, type: "number", options: intOpts },
      { name: F.OpenRoles.RECRUITER, type: "singleLineText" },
      { name: F.OpenRoles.HIRING_MANAGER, type: "singleLineText" },
      { name: F.OpenRoles.DATE_POSTED, type: "date", options: dateOpts },
      { name: F.OpenRoles.DATE_CLOSED, type: "date", options: dateOpts },
      {
        name: F.OpenRoles.EMPLOYMENT_TYPE,
        type: "singleSelect",
        options: choices(["Full-time", "Part-time", "Contract", "Reliever", "Locum"]),
      },
      { name: F.OpenRoles.NOTES, type: "multilineText" },
      { name: F.OpenRoles.REQUISITION, type: "multipleRecordLinks", linkedTable: "Requisitions" },
      { name: F.OpenRoles.REQ_SUBMITTER_NAME, type: "singleLineText" },
      { name: F.OpenRoles.REQ_SUBMITTER_EMAIL, type: "email" },
    ],
  },
  {
    name: "Candidates",
    fields: [
      { name: F.Candidates.CAND_ID, type: "singleLineText" },
      { name: F.Candidates.NAME, type: "singleLineText" },
      { name: F.Candidates.PHONE, type: "phoneNumber" },
      { name: F.Candidates.EMAIL, type: "email" },
      { name: F.Candidates.ROLE, type: "multipleRecordLinks", linkedTable: "Open Roles" },
      {
        name: F.Candidates.STAGE,
        type: "singleSelect",
        options: choices([
          "First Interview", "Second Interview", "Panel Interview", "Work Trial",
          "Reference Check", "Offer", "Hired", "Backup Pool", "Rejected", "Withdrawn",
        ]),
      },
      { name: F.Candidates.SOURCE, type: "singleLineText" },
      { name: F.Candidates.GENDER, type: "singleSelect", options: choices(["Male", "Female"]) },
      {
        name: F.Candidates.EMPLOYMENT_TYPE,
        type: "singleSelect",
        options: choices(["Full-time", "Part-time", "Contract", "Reliever", "Locum"]),
      },
      { name: F.Candidates.REFEREE1_NAME, type: "singleLineText" },
      { name: F.Candidates.REFEREE1_EMAIL, type: "email" },
      { name: F.Candidates.REFEREE1_PHONE, type: "phoneNumber" },
      { name: F.Candidates.REFEREE2_NAME, type: "singleLineText" },
      { name: F.Candidates.REFEREE2_EMAIL, type: "email" },
      { name: F.Candidates.REFEREE2_PHONE, type: "phoneNumber" },
      {
        name: F.Candidates.WORK_TRIAL_STATUS,
        type: "singleSelect",
        options: choices(["Scheduled", "Awaiting Arrival", "Awaiting Score", "Complete"]),
      },
      { name: F.Candidates.REF_CHECK_STATUS, type: "singleLineText" },
      {
        name: F.Candidates.OFFER_STATUS,
        type: "singleSelect",
        options: choices(["Pending", "Accepted", "Declined", "Negotiating", "Withdrawn"]),
      },
      { name: F.Candidates.JOINED, type: "singleSelect", options: choices(["Pending", "Joined", "Did Not Join"]) },
      { name: F.Candidates.STAGE_ENTERED_AT, type: "date", options: dateOpts },
      { name: F.Candidates.CREATED_AT, type: "date", options: dateOpts },
    ],
  },
  {
    name: "Interviews",
    fields: [
      { name: F.Interviews.SCHED_ID, type: "singleLineText" },
      { name: F.Interviews.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.Interviews.ROLE, type: "multipleRecordLinks", linkedTable: "Open Roles" },
      { name: F.Interviews.DATE, type: "date", options: dateOpts },
      { name: F.Interviews.TIME, type: "singleLineText" },
      { name: F.Interviews.WEEK_LABEL, type: "singleLineText" },
      { name: F.Interviews.MONTH, type: "singleLineText" },
      { name: F.Interviews.STAGE, type: "singleSelect", options: choices(["First Interview", "Second Interview", "Panel Interview"]) },
      { name: F.Interviews.TYPE, type: "singleSelect", options: choices(["In-person", "Google Meet", "Phone", "WhatsApp"]) },
      { name: F.Interviews.LOCATION, type: "singleLineText" },
      { name: F.Interviews.INTERVIEWERS, type: "multilineText" },
      { name: F.Interviews.CONFIRMED, type: "checkbox", options: checkboxOpts },
      { name: F.Interviews.REMINDER_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.Interviews.ATTENDANCE, type: "singleSelect", options: choices(["Attended", "No-show", "Pending"]) },
      { name: F.Interviews.OUTCOME, type: "singleSelect", options: choices(["Pass", "Fail", "Pending"]) },
      { name: F.Interviews.NOTES, type: "multilineText" },
    ],
  },
  {
    name: "Work Trials",
    fields: [
      { name: F.WorkTrials.WT_ID, type: "singleLineText" },
      { name: F.WorkTrials.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.WorkTrials.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      { name: F.WorkTrials.DATE, type: "date", options: dateOpts },
      { name: F.WorkTrials.SUPERVISOR, type: "singleLineText" },
      { name: F.WorkTrials.ARRIVAL_MARKED, type: "singleSelect", options: choices(["Arrived", "Not Arrived", "Pending"]) },
      { name: F.WorkTrials.SCORE_TECHNICAL, type: "number", options: scoreOpts },
      { name: F.WorkTrials.SCORE_PATIENT, type: "number", options: scoreOpts },
      { name: F.WorkTrials.SCORE_SAFETY, type: "number", options: scoreOpts },
      { name: F.WorkTrials.SCORE_CULTURE, type: "number", options: scoreOpts },
      { name: F.WorkTrials.TOTAL, type: "number", options: scoreOpts },
      { name: F.WorkTrials.PASS_FAIL, type: "singleSelect", options: choices(["Pass", "Fail", "Pending"]) },
      { name: F.WorkTrials.FORM_SUBMITTED_AT, type: "date", options: dateOpts },
      { name: F.WorkTrials.REMINDER_12H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.WorkTrials.ESCALATION_24H_SENT, type: "checkbox", options: checkboxOpts },
    ],
  },
  {
    name: "Reference Checks",
    fields: [
      { name: F.ReferenceChecks.REF_ID, type: "singleLineText" },
      { name: F.ReferenceChecks.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.ReferenceChecks.REFEREE1_NAME, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE1_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE1_PHONE, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE1_EMAIL_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_SMS_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_RESPONDED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_RESPONDED_AT, type: "date", options: dateOpts },
      {
        name: F.ReferenceChecks.REFEREE1_RELATIONSHIP,
        type: "singleSelect",
        options: choices(["Direct manager", "Senior colleague", "Peer / colleague", "Client or patient", "Other professional"]),
      },
      {
        name: F.ReferenceChecks.REFEREE1_DURATION_KNOWN,
        type: "singleSelect",
        options: choices(["Less than 1 year", "1-2 years", "2-5 years", "5+ years"]),
      },
      { name: F.ReferenceChecks.REFEREE1_TECH_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE1_RELIABILITY_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE1_TEAMWORK_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE1_WOULD_REHIRE,
        type: "singleSelect",
        options: choices(["Yes, without hesitation", "Yes, with some reservations", "No, I would not recommend them"]),
      },
      { name: F.ReferenceChecks.REFEREE1_STRENGTH_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_DEVELOPMENT_AREAS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_NOTES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_NAME, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE2_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE2_PHONE, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE2_EMAIL_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_SMS_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_RESPONDED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_RESPONDED_AT, type: "date", options: dateOpts },
      {
        name: F.ReferenceChecks.REFEREE2_RELATIONSHIP,
        type: "singleSelect",
        options: choices(["Direct manager", "Senior colleague", "Peer / colleague", "Client or patient", "Other professional"]),
      },
      {
        name: F.ReferenceChecks.REFEREE2_DURATION_KNOWN,
        type: "singleSelect",
        options: choices(["Less than 1 year", "1-2 years", "2-5 years", "5+ years"]),
      },
      { name: F.ReferenceChecks.REFEREE2_TECH_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE2_RELIABILITY_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE2_TEAMWORK_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE2_WOULD_REHIRE,
        type: "singleSelect",
        options: choices(["Yes, without hesitation", "Yes, with some reservations", "No, I would not recommend them"]),
      },
      { name: F.ReferenceChecks.REFEREE2_STRENGTH_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_DEVELOPMENT_AREAS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_NOTES, type: "multilineText" },
      { name: F.ReferenceChecks.OUTCOME, type: "singleSelect", options: choices(["Pending", "Positive", "Negative", "Mixed"]) },
      { name: F.ReferenceChecks.DRIVE_FOLDER_URL, type: "url" },
      { name: F.ReferenceChecks.CREATED_AT, type: "date", options: dateOpts },
    ],
  },
  {
    name: "Offers",
    fields: [
      { name: F.Offers.OFFER_ID, type: "singleLineText" },
      { name: F.Offers.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.Offers.OFFERED_SALARY, type: "currency", options: currencyOpts },
      { name: F.Offers.BUDGETED_SALARY, type: "currency", options: currencyOpts },
      { name: F.Offers.DATE_SENT, type: "date", options: dateOpts },
      { name: F.Offers.DEADLINE, type: "date", options: dateOpts },
      { name: F.Offers.OUTCOME, type: "singleSelect", options: choices(["Pending", "Accepted", "Declined", "Negotiating", "Withdrawn"]) },
      { name: F.Offers.COUNTER_OFFER_AMOUNT, type: "currency", options: currencyOpts },
      { name: F.Offers.FINAL_ACCEPTED_SALARY, type: "currency", options: currencyOpts },
      { name: F.Offers.START_DATE, type: "date", options: dateOpts },
      { name: F.Offers.JOINED, type: "singleSelect", options: choices(["Pending", "Joined", "Did Not Join"]) },
      { name: F.Offers.DROP_REASON, type: "multilineText" },
    ],
  },
  {
    name: "New Employees",
    fields: [
      { name: F.NewEmployees.EMPLOYEE_ID, type: "singleLineText" },
      { name: F.NewEmployees.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.NewEmployees.NAME, type: "singleLineText" },
      { name: F.NewEmployees.ROLE, type: "singleLineText" },
      { name: F.NewEmployees.DEPARTMENT, type: "singleLineText" },
      { name: F.NewEmployees.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      { name: F.NewEmployees.START_DATE, type: "date", options: dateOpts },
      {
        name: F.NewEmployees.EMPLOYMENT_TYPE,
        type: "singleSelect",
        options: choices(["Full-time", "Part-time", "Contract", "Reliever", "Locum"]),
      },
      { name: F.NewEmployees.CONTRACT_END, type: "date", options: dateOpts },
      {
        name: F.NewEmployees.CONFIRMATION_6MO,
        type: "singleSelect",
        options: choices(["Pending", "Confirmed", "Not Confirmed"]),
      },
      { name: F.NewEmployees.CONFIRMATION_6MO_AT, type: "date", options: dateOpts },
      { name: F.NewEmployees.REQ_SUBMITTER_NAME, type: "singleLineText" },
      { name: F.NewEmployees.REQ_SUBMITTER_EMAIL, type: "email" },
    ],
  },
  {
    name: "Relievers",
    fields: [
      { name: F.Relievers.RELIEVER_ID, type: "singleLineText" },
      { name: F.Relievers.NAME, type: "singleLineText" },
      { name: F.Relievers.ROLE, type: "singleSelect", options: choices(RELIEVER_CADRES) },
      { name: F.Relievers.BRANCHES_COVERED, type: "multipleSelects", options: choices(ALL_BRANCHES) },
      { name: F.Relievers.AVAILABILITY_DATES, type: "singleLineText" },
      { name: F.Relievers.STATUS, type: "singleSelect", options: choices(["Active", "Inactive"]) },
      { name: F.Relievers.PHONE, type: "phoneNumber" },
      { name: F.Relievers.NOTES, type: "multilineText" },
    ],
  },
  {
    name: "Locums",
    fields: [
      { name: F.Locums.LOCUM_ID, type: "singleLineText" },
      { name: F.Locums.NAME, type: "singleLineText" },
      {
        name: F.Locums.SPECIALITY,
        type: "singleSelect",
        options: choices(["General Practice", "Dental", "Pharmacy", "Sonography"]),
      },
      { name: F.Locums.BRANCHES_COVERED, type: "multipleSelects", options: choices(COVERAGE_ZONES) },
      { name: F.Locums.DAILY_RATE, type: "currency", options: currencyOpts },
      { name: F.Locums.LICENSE_NUMBER, type: "singleLineText" },
      { name: F.Locums.AVAILABILITY, type: "singleLineText" },
      { name: F.Locums.LAST_DEPLOYED, type: "date", options: dateOpts },
    ],
  },
];

module.exports = { TABLES, F };
