// Single source of truth for the 11 Airtable tables that mirror src/types.ts.
// Both build-airtable-schema.js (creates tables/fields) and seed-airtable.js
// (writes records) import the field-name constants from here so the two
// scripts can never drift out of sync with each other.

const dateOpts = { dateFormat: { name: "iso", format: "YYYY-MM-DD" } };
const checkboxOpts = { icon: "check", color: "greenBright" };
const currencyOpts = { symbol: "KES ", precision: 0 };
const intOpts = { precision: 0 };
const scoreOpts = { precision: 1 };
// Headcount numbers that can legitimately be halves (a role split across
// two clustered branches) — same shape as scoreOpts, named for what it's
// actually used for here.
const decimalOpts = { precision: 1 };

// Reference Checks single-select option sets shared across all 4 REFEREE{N}_*
// slots (see mirrored src/lib/airtable/field-names.ts / src/types.ts).
const REPORTING_RELATIONSHIP_OPTIONS = [
  "Reported directly to me",
  "Reported to someone else, but I worked closely with them",
  "We were peers / colleagues",
  "I reported to them",
];
const INTERACTION_FREQUENCY_OPTIONS = ["Daily", "A few times a week", "Weekly", "A few times a month", "Rarely"];
const LEAVING_REASON_OPTIONS = ["Still employed there", "Resigned", "Contract ended", "Laid off / restructuring", "Terminated", "Not sure"];
// First 3 are what the current (Sept 2026) /referee redesign writes; the
// rest are legacy values from two earlier generations of this form, kept so
// the live single-select never orphans historical data (see SETUP.md).
const WOULD_REHIRE_OPTIONS = [
  "Yes",
  "With reservations",
  "No",
  "Yes, without hesitation",
  "Yes, with reservations",
  "Unsure",
  "Yes, with some reservations",
  "No, I would not recommend them",
];
const FEEDBACK_RESPONSE_OPTIONS = ["Openly, and applied it", "Mixed", "Defensively"];
const RECOMMEND_HIRE_OPTIONS = ["Strongly Recommend", "Recommend", "Recommend with Reservations", "Do Not Recommend"];

// Mirrors src/lib/mock-data/clusters.ts. Duplicated here (rather than
// imported) because this script runs as plain CommonJS outside the Next.js
// TS pipeline. Airtable inserts use typecast: true, so any reliever/locum
// branch not listed below is still added automatically during seeding.
const RELIEVER_CADRES = [
  "Clinical Coordinator",
  "Clinical Officer",
  "Pharm Tech",
  "Lab Technician",
  "Nurse",
  "Sonographer",
];
const COVERAGE_ZONES = ["Eastleigh", "Waiyaki Way", "Utawala", "Thika Road", "Langata", "Kitengela"];

// The 5 cadres tracked by the Staffing Projections feature — shared between
// Open Roles' Cadre field and the Staffing Projections table's own Cadre
// field so a role and a projection can be matched on an identical value.
// Short codes match how People Ops already refers to them, not the longer
// RELIEVER_CADRES names above (that table predates this feature).
const CADRES = ["CC", "Labtech", "Nurse", "Pharmtech", "Clinical Officer"];
const ALL_BRANCHES = [
  "Umoja 1", "Umoja 2", "Pipeline", "Tassia", "Embakasi",
  "Kangemi", "Kawangware", "Kimathi",
  "Shooters", "Benedicata", "Kariobangi South",
  "Kahawa West", "Zimmerman", "Githurai 45", "Sunton", "Luckysummer",
  "Langata", "Kitengela",
];

function choices(names) {
  return { choices: names.map((name) => ({ name })) };
}

const F = {
  Branches: {
    BRANCH_ID: "Branch ID",
    NAME: "Name",
    CITY: "City",
    REGION: "Region",
    BRANCH_MANAGER: "Branch Manager",
    BM_EMAIL: "BM Email",
    BM_PHONE: "BM Phone",
    REGIONAL_MANAGER: "Regional Manager",
    CAPACITY: "Capacity",
    ACTIVE: "Active",
    // Was missing from this table's field list below (field-names.ts had it,
    // this script didn't) — a fresh base built via this script alone would
    // have been unable to write it. Added alongside EXPANSION_BRANCH.
    WORK_TRIAL_ACTIVE: "Work Trial Active",
    ADDRESS: "Address",
    MAP_PIN_URL: "Map Pin URL",
    EXPANSION_BRANCH: "Expansion Branch",
    SEGMENT: "Segment",
  },
  Requisitions: {
    REQ_ID: "Req ID",
    TYPE: "Type",
    ROLE_TITLE: "Role Title",
    DEPARTMENT: "Department",
    SEGMENT: "Segment",
    GAP_REASON: "Gap Reason",
    REASON_TYPE: "Reason Type",
    BRANCH: "Branch",
    EMPLOYMENT_TYPE: "Employment Type",
    LEVEL: "Level",
    HEADCOUNT: "Headcount",
    JUSTIFICATION: "Justification",
    SALARY_MIN: "Salary Range Min",
    SALARY_MAX: "Salary Range Max",
    URGENCY: "Urgency",
    JD_ATTACHED: "JD Attached",
    JD_URL: "JD URL",
    STATUS: "Status",
    APPROVER_CHAIN: "Approver Chain",
    CURRENT_APPROVER_INDEX: "Current Approver Index",
    SUBMITTED_BY: "Submitted By",
    SUBMITTED_AT: "Submitted At",
    EXPECTED_START_DATE: "Expected Start Date",
    CONTEXT: "Context",
    SUBMITTER_NAME: "Submitter Name",
    SUBMITTER_EMAIL: "Submitter Email",
    SUBMITTER_ROLE: "Submitter Role",
    SOURCE: "Source",
    BUDGET_EVALUATION_CONFIRMED: "Budget Evaluation Confirmed",
  },
  OpenRoles: {
    ROLE_ID: "Role ID",
    TITLE: "Title",
    SEGMENT: "Segment",
    DEPARTMENT: "Department",
    LOCATION: "Location",
    BRANCH: "Branch",
    PRIORITY: "Priority",
    STATUS: "Status",
    HC_APPROVED: "HC Approved",
    HC_FILLED: "HC Filled",
    RECRUITER: "Recruiter",
    HIRING_MANAGER: "Hiring Manager",
    HIRING_MANAGER_EMAIL: "Hiring Manager Email",
    DATE_POSTED: "Date Posted",
    DATE_CLOSED: "Date Closed",
    EMPLOYMENT_TYPE: "Employment Type",
    NOTES: "Notes",
    // Same drift as WORK_TRIAL_ACTIVE above — field-names.ts already had
    // these, this script's table def didn't.
    INTERNAL_FILL: "Internal Fill",
    INTERNAL_FILL_NAME: "Internal Fill Name",
    REQUISITION: "Requisition",
    REQ_SUBMITTER_NAME: "Requisition Submitter Name",
    REQ_SUBMITTER_EMAIL: "Requisition Submitter Email",
    REPLACEMENT_REQUISITION: "Replacement Requisition",
    // Which of the 5 tracked cadres this role belongs to — blank for roles
    // outside those 5 (Dentist, IT, admin, etc). Feeds the Staffing
    // Projections page's Required HC (= sum of hcApproved per branch+cadre).
    CADRE: "Cadre",
  },
  Candidates: {
    CAND_ID: "Cand ID",
    NAME: "Name",
    PHONE: "Phone",
    EMAIL: "Email",
    ROLE: "Role",
    STAGE: "Stage",
    SOURCE: "Source",
    GENDER: "Gender",
    EMPLOYMENT_TYPE: "Employment Type",
    REFEREE1_NAME: "Referee 1 Name",
    REFEREE1_EMAIL: "Referee 1 Email",
    REFEREE1_PHONE: "Referee 1 Phone",
    REFEREE2_NAME: "Referee 2 Name",
    REFEREE2_EMAIL: "Referee 2 Email",
    REFEREE2_PHONE: "Referee 2 Phone",
    WORK_TRIAL_STATUS: "Work Trial Status",
    REF_CHECK_STATUS: "Ref Check Status",
    OFFER_STATUS: "Offer Status",
    JOINED: "Joined",
    STAGE_ENTERED_AT: "Stage Entered At",
    CREATED_AT: "Created At",
  },
  Interviews: {
    SCHED_ID: "Sched ID",
    CANDIDATE: "Candidate",
    ROLE: "Role",
    DATE: "Date",
    TIME: "Time",
    WEEK_LABEL: "Week Label",
    MONTH: "Month",
    STAGE: "Stage",
    TYPE: "Type",
    LOCATION: "Location",
    INTERVIEWERS: "Interviewers",
    CONFIRMED: "Confirmed",
    REMINDER_SENT: "Reminder Sent",
    ATTENDANCE: "Attendance",
    OUTCOME: "Outcome",
    NOTES: "Notes",
  },
  WorkTrials: {
    WT_ID: "WT ID",
    CANDIDATE: "Candidate",
    ROLE: "Role",
    BRANCH: "Branch",
    DATE: "Date",
    SUPERVISOR: "Supervisor",
    CREATED_AT: "Created At",
    ARRIVAL_MARKED: "Arrival Marked",
    SCORE_TECHNICAL: "Score Technical",
    SCORE_PATIENT: "Score Patient",
    SCORE_SAFETY: "Score Safety",
    SCORE_CULTURE: "Score Culture",
    TOTAL: "Total",
    PASS_FAIL: "Pass/Fail",
    FORM_SUBMITTED_AT: "Form Submitted At",
    SUBMITTED_BY_ROLE: "Submitted By Role",
    BM_APPROVED_AT: "BM Approved At",
    BM_SCORING_LINK: "BM Scoring Link",
    REMINDER_12H_SENT: "Reminder 12h Sent",
    ESCALATION_24H_SENT: "Escalation 24h Sent",
    COMMENT_CULTURE: "Comment Culture",
    COMMENT_PATIENT: "Comment Patient",
    COMMENT_TECHNICAL: "Comment Technical",
    STRENGTHS: "Strengths",
    AREAS_OF_DEVELOPMENT: "Areas of Development",
    OVERALL_RECOMMENDATION: "Overall Recommendation",
    SUBMISSION_METHOD: "Submission Method",
    UPLOADED_FORM: "Uploaded Form",
  },
  ReferenceChecks: {
    REF_ID: "Ref ID",
    CANDIDATE: "Candidate",
    REFEREE1_NAME: "Referee 1 Name",
    REFEREE1_EMAIL: "Referee 1 Email",
    REFEREE1_PHONE: "Referee 1 Phone",
    REFEREE1_EMAIL_SENT: "Referee 1 Email Sent",
    REFEREE1_SMS_SENT: "Referee 1 SMS Sent",
    REFEREE1_RESPONDED: "Referee 1 Responded",
    REFEREE1_RESPONDED_AT: "Referee 1 Responded At",
    REFEREE1_RELATIONSHIP: "Referee 1 Relationship",
    REFEREE1_DIRECTLY_SUPERVISED: "Referee 1 Directly Supervised",
    REFEREE1_REPORTING_RELATIONSHIP: "Referee 1 Reporting Relationship",
    REFEREE1_ORGANIZATION: "Referee 1 Organization",
    REFEREE1_DURATION_KNOWN: "Referee 1 Duration Known",
    REFEREE1_INTERACTION_FREQUENCY: "Referee 1 Interaction Frequency",
    REFEREE1_JOB_TITLE_RECALLED: "Referee 1 Job Title Recalled",
    REFEREE1_EMPLOYMENT_FROM: "Referee 1 Employment From",
    REFEREE1_EMPLOYMENT_TO: "Referee 1 Employment To",
    REFEREE1_STILL_EMPLOYED: "Referee 1 Still Employed",
    REFEREE1_MAIN_RESPONSIBILITIES: "Referee 1 Main Responsibilities",
    REFEREE1_REPORTED_TO: "Referee 1 Reported To",
    REFEREE1_LEAVING_REASON: "Referee 1 Leaving Reason",
    REFEREE1_TECH_SCORE: "Referee 1 Tech Score",
    REFEREE1_RELIABILITY_SCORE: "Referee 1 Reliability Score",
    REFEREE1_EXECUTION_SCORE: "Referee 1 Execution Score",
    REFEREE1_EXECUTION_EXAMPLE: "Referee 1 Execution Example",
    REFEREE1_TEAMWORK_SCORE: "Referee 1 Teamwork Score",
    REFEREE1_TEAMWORK_EXAMPLE: "Referee 1 Teamwork Example",
    REFEREE1_COMMUNICATION_SCORE: "Referee 1 Communication Score",
    REFEREE1_COMMUNICATION_EXAMPLE: "Referee 1 Communication Example",
    REFEREE1_PROBLEM_SOLVING_SCORE: "Referee 1 Problem Solving Score",
    REFEREE1_ADAPTABILITY_SCORE: "Referee 1 Adaptability Score",
    REFEREE1_WOULD_REHIRE: "Referee 1 Would Rehire",
    REFEREE1_WOULD_REHIRE_EXPLANATION: "Referee 1 Would Rehire Explanation",
    REFEREE1_STRENGTH_EXAMPLE: "Referee 1 Strength Example",
    REFEREE1_DEVELOPMENT_AREAS: "Referee 1 Development Areas",
    REFEREE1_STRENGTHS_AND_DEVELOPMENT: "Referee 1 Strengths And Development",
    REFEREE1_TOP_STRENGTHS: "Referee 1 Top Strengths",
    REFEREE1_COACHING_AREA: "Referee 1 Coaching Area",
    REFEREE1_FEEDBACK_RESPONSE: "Referee 1 Feedback Response",
    REFEREE1_CONFLICT_EXAMPLE: "Referee 1 Conflict Example",
    REFEREE1_HONESTY_CONCERNS: "Referee 1 Honesty Concerns",
    REFEREE1_COMPLIANCE_INCIDENTS: "Referee 1 Compliance Incidents",
    REFEREE1_LICENSE_STANDING: "Referee 1 License Standing",
    REFEREE1_PREFER_PHONE_NUMBER: "Referee 1 Prefer Phone Number",
    REFEREE1_OVERALL_RECOMMEND_SCORE: "Referee 1 Overall Recommend Score",
    REFEREE1_RECOMMEND_HIRE: "Referee 1 Recommend Hire",
    REFEREE1_CONSENT_TO_CONTACT: "Referee 1 Consent To Contact",
    REFEREE1_NOTES: "Referee 1 Notes",
    REFEREE1_GOOGLE_VERIFIED: "Referee 1 Google Verified",
    REFEREE1_GOOGLE_VERIFIED_EMAIL: "Referee 1 Google Verified Email",
    REFEREE1_GOOGLE_VERIFIED_OVERRIDE_BY: "Referee 1 Google Verified Override By",
    REFEREE1_REMINDER_24H_SENT: "Referee 1 Reminder 24h Sent",
    REFEREE1_REMINDER_48H_SENT: "Referee 1 Reminder 48h Sent",
    REFEREE2_NAME: "Referee 2 Name",
    REFEREE2_EMAIL: "Referee 2 Email",
    REFEREE2_PHONE: "Referee 2 Phone",
    REFEREE2_EMAIL_SENT: "Referee 2 Email Sent",
    REFEREE2_SMS_SENT: "Referee 2 SMS Sent",
    REFEREE2_RESPONDED: "Referee 2 Responded",
    REFEREE2_RESPONDED_AT: "Referee 2 Responded At",
    REFEREE2_RELATIONSHIP: "Referee 2 Relationship",
    REFEREE2_DIRECTLY_SUPERVISED: "Referee 2 Directly Supervised",
    REFEREE2_REPORTING_RELATIONSHIP: "Referee 2 Reporting Relationship",
    REFEREE2_ORGANIZATION: "Referee 2 Organization",
    REFEREE2_DURATION_KNOWN: "Referee 2 Duration Known",
    REFEREE2_INTERACTION_FREQUENCY: "Referee 2 Interaction Frequency",
    REFEREE2_JOB_TITLE_RECALLED: "Referee 2 Job Title Recalled",
    REFEREE2_EMPLOYMENT_FROM: "Referee 2 Employment From",
    REFEREE2_EMPLOYMENT_TO: "Referee 2 Employment To",
    REFEREE2_STILL_EMPLOYED: "Referee 2 Still Employed",
    REFEREE2_MAIN_RESPONSIBILITIES: "Referee 2 Main Responsibilities",
    REFEREE2_REPORTED_TO: "Referee 2 Reported To",
    REFEREE2_LEAVING_REASON: "Referee 2 Leaving Reason",
    REFEREE2_TECH_SCORE: "Referee 2 Tech Score",
    REFEREE2_RELIABILITY_SCORE: "Referee 2 Reliability Score",
    REFEREE2_EXECUTION_SCORE: "Referee 2 Execution Score",
    REFEREE2_EXECUTION_EXAMPLE: "Referee 2 Execution Example",
    REFEREE2_TEAMWORK_SCORE: "Referee 2 Teamwork Score",
    REFEREE2_TEAMWORK_EXAMPLE: "Referee 2 Teamwork Example",
    REFEREE2_COMMUNICATION_SCORE: "Referee 2 Communication Score",
    REFEREE2_COMMUNICATION_EXAMPLE: "Referee 2 Communication Example",
    REFEREE2_PROBLEM_SOLVING_SCORE: "Referee 2 Problem Solving Score",
    REFEREE2_ADAPTABILITY_SCORE: "Referee 2 Adaptability Score",
    REFEREE2_WOULD_REHIRE: "Referee 2 Would Rehire",
    REFEREE2_WOULD_REHIRE_EXPLANATION: "Referee 2 Would Rehire Explanation",
    REFEREE2_STRENGTH_EXAMPLE: "Referee 2 Strength Example",
    REFEREE2_DEVELOPMENT_AREAS: "Referee 2 Development Areas",
    REFEREE2_STRENGTHS_AND_DEVELOPMENT: "Referee 2 Strengths And Development",
    REFEREE2_TOP_STRENGTHS: "Referee 2 Top Strengths",
    REFEREE2_COACHING_AREA: "Referee 2 Coaching Area",
    REFEREE2_FEEDBACK_RESPONSE: "Referee 2 Feedback Response",
    REFEREE2_CONFLICT_EXAMPLE: "Referee 2 Conflict Example",
    REFEREE2_HONESTY_CONCERNS: "Referee 2 Honesty Concerns",
    REFEREE2_COMPLIANCE_INCIDENTS: "Referee 2 Compliance Incidents",
    REFEREE2_LICENSE_STANDING: "Referee 2 License Standing",
    REFEREE2_PREFER_PHONE_NUMBER: "Referee 2 Prefer Phone Number",
    REFEREE2_OVERALL_RECOMMEND_SCORE: "Referee 2 Overall Recommend Score",
    REFEREE2_RECOMMEND_HIRE: "Referee 2 Recommend Hire",
    REFEREE2_CONSENT_TO_CONTACT: "Referee 2 Consent To Contact",
    REFEREE2_NOTES: "Referee 2 Notes",
    REFEREE2_GOOGLE_VERIFIED: "Referee 2 Google Verified",
    REFEREE2_GOOGLE_VERIFIED_EMAIL: "Referee 2 Google Verified Email",
    REFEREE2_GOOGLE_VERIFIED_OVERRIDE_BY: "Referee 2 Google Verified Override By",
    REFEREE2_REMINDER_24H_SENT: "Referee 2 Reminder 24h Sent",
    REFEREE2_REMINDER_48H_SENT: "Referee 2 Reminder 48h Sent",
    REFEREE3_NAME: "Referee 3 Name",
    REFEREE3_EMAIL: "Referee 3 Email",
    REFEREE3_PHONE: "Referee 3 Phone",
    REFEREE3_EMAIL_SENT: "Referee 3 Email Sent",
    REFEREE3_SMS_SENT: "Referee 3 SMS Sent",
    REFEREE3_RESPONDED: "Referee 3 Responded",
    REFEREE3_RESPONDED_AT: "Referee 3 Responded At",
    REFEREE3_RELATIONSHIP: "Referee 3 Relationship",
    REFEREE3_DIRECTLY_SUPERVISED: "Referee 3 Directly Supervised",
    REFEREE3_REPORTING_RELATIONSHIP: "Referee 3 Reporting Relationship",
    REFEREE3_ORGANIZATION: "Referee 3 Organization",
    REFEREE3_DURATION_KNOWN: "Referee 3 Duration Known",
    REFEREE3_INTERACTION_FREQUENCY: "Referee 3 Interaction Frequency",
    REFEREE3_JOB_TITLE_RECALLED: "Referee 3 Job Title Recalled",
    REFEREE3_EMPLOYMENT_FROM: "Referee 3 Employment From",
    REFEREE3_EMPLOYMENT_TO: "Referee 3 Employment To",
    REFEREE3_STILL_EMPLOYED: "Referee 3 Still Employed",
    REFEREE3_MAIN_RESPONSIBILITIES: "Referee 3 Main Responsibilities",
    REFEREE3_REPORTED_TO: "Referee 3 Reported To",
    REFEREE3_LEAVING_REASON: "Referee 3 Leaving Reason",
    REFEREE3_TECH_SCORE: "Referee 3 Tech Score",
    REFEREE3_RELIABILITY_SCORE: "Referee 3 Reliability Score",
    REFEREE3_EXECUTION_SCORE: "Referee 3 Execution Score",
    REFEREE3_EXECUTION_EXAMPLE: "Referee 3 Execution Example",
    REFEREE3_TEAMWORK_SCORE: "Referee 3 Teamwork Score",
    REFEREE3_TEAMWORK_EXAMPLE: "Referee 3 Teamwork Example",
    REFEREE3_COMMUNICATION_SCORE: "Referee 3 Communication Score",
    REFEREE3_COMMUNICATION_EXAMPLE: "Referee 3 Communication Example",
    REFEREE3_PROBLEM_SOLVING_SCORE: "Referee 3 Problem Solving Score",
    REFEREE3_ADAPTABILITY_SCORE: "Referee 3 Adaptability Score",
    REFEREE3_WOULD_REHIRE: "Referee 3 Would Rehire",
    REFEREE3_WOULD_REHIRE_EXPLANATION: "Referee 3 Would Rehire Explanation",
    REFEREE3_STRENGTH_EXAMPLE: "Referee 3 Strength Example",
    REFEREE3_DEVELOPMENT_AREAS: "Referee 3 Development Areas",
    REFEREE3_STRENGTHS_AND_DEVELOPMENT: "Referee 3 Strengths And Development",
    REFEREE3_TOP_STRENGTHS: "Referee 3 Top Strengths",
    REFEREE3_COACHING_AREA: "Referee 3 Coaching Area",
    REFEREE3_FEEDBACK_RESPONSE: "Referee 3 Feedback Response",
    REFEREE3_CONFLICT_EXAMPLE: "Referee 3 Conflict Example",
    REFEREE3_HONESTY_CONCERNS: "Referee 3 Honesty Concerns",
    REFEREE3_COMPLIANCE_INCIDENTS: "Referee 3 Compliance Incidents",
    REFEREE3_LICENSE_STANDING: "Referee 3 License Standing",
    REFEREE3_PREFER_PHONE_NUMBER: "Referee 3 Prefer Phone Number",
    REFEREE3_OVERALL_RECOMMEND_SCORE: "Referee 3 Overall Recommend Score",
    REFEREE3_RECOMMEND_HIRE: "Referee 3 Recommend Hire",
    REFEREE3_CONSENT_TO_CONTACT: "Referee 3 Consent To Contact",
    REFEREE3_NOTES: "Referee 3 Notes",
    REFEREE3_GOOGLE_VERIFIED: "Referee 3 Google Verified",
    REFEREE3_GOOGLE_VERIFIED_EMAIL: "Referee 3 Google Verified Email",
    REFEREE3_GOOGLE_VERIFIED_OVERRIDE_BY: "Referee 3 Google Verified Override By",
    REFEREE3_REMINDER_24H_SENT: "Referee 3 Reminder 24h Sent",
    REFEREE3_REMINDER_48H_SENT: "Referee 3 Reminder 48h Sent",
    REFEREE4_NAME: "Referee 4 Name",
    REFEREE4_EMAIL: "Referee 4 Email",
    REFEREE4_PHONE: "Referee 4 Phone",
    REFEREE4_EMAIL_SENT: "Referee 4 Email Sent",
    REFEREE4_SMS_SENT: "Referee 4 SMS Sent",
    REFEREE4_RESPONDED: "Referee 4 Responded",
    REFEREE4_RESPONDED_AT: "Referee 4 Responded At",
    REFEREE4_RELATIONSHIP: "Referee 4 Relationship",
    REFEREE4_DIRECTLY_SUPERVISED: "Referee 4 Directly Supervised",
    REFEREE4_REPORTING_RELATIONSHIP: "Referee 4 Reporting Relationship",
    REFEREE4_ORGANIZATION: "Referee 4 Organization",
    REFEREE4_DURATION_KNOWN: "Referee 4 Duration Known",
    REFEREE4_INTERACTION_FREQUENCY: "Referee 4 Interaction Frequency",
    REFEREE4_JOB_TITLE_RECALLED: "Referee 4 Job Title Recalled",
    REFEREE4_EMPLOYMENT_FROM: "Referee 4 Employment From",
    REFEREE4_EMPLOYMENT_TO: "Referee 4 Employment To",
    REFEREE4_STILL_EMPLOYED: "Referee 4 Still Employed",
    REFEREE4_MAIN_RESPONSIBILITIES: "Referee 4 Main Responsibilities",
    REFEREE4_REPORTED_TO: "Referee 4 Reported To",
    REFEREE4_LEAVING_REASON: "Referee 4 Leaving Reason",
    REFEREE4_TECH_SCORE: "Referee 4 Tech Score",
    REFEREE4_RELIABILITY_SCORE: "Referee 4 Reliability Score",
    REFEREE4_EXECUTION_SCORE: "Referee 4 Execution Score",
    REFEREE4_EXECUTION_EXAMPLE: "Referee 4 Execution Example",
    REFEREE4_TEAMWORK_SCORE: "Referee 4 Teamwork Score",
    REFEREE4_TEAMWORK_EXAMPLE: "Referee 4 Teamwork Example",
    REFEREE4_COMMUNICATION_SCORE: "Referee 4 Communication Score",
    REFEREE4_COMMUNICATION_EXAMPLE: "Referee 4 Communication Example",
    REFEREE4_PROBLEM_SOLVING_SCORE: "Referee 4 Problem Solving Score",
    REFEREE4_ADAPTABILITY_SCORE: "Referee 4 Adaptability Score",
    REFEREE4_WOULD_REHIRE: "Referee 4 Would Rehire",
    REFEREE4_WOULD_REHIRE_EXPLANATION: "Referee 4 Would Rehire Explanation",
    REFEREE4_STRENGTH_EXAMPLE: "Referee 4 Strength Example",
    REFEREE4_DEVELOPMENT_AREAS: "Referee 4 Development Areas",
    REFEREE4_STRENGTHS_AND_DEVELOPMENT: "Referee 4 Strengths And Development",
    REFEREE4_TOP_STRENGTHS: "Referee 4 Top Strengths",
    REFEREE4_COACHING_AREA: "Referee 4 Coaching Area",
    REFEREE4_FEEDBACK_RESPONSE: "Referee 4 Feedback Response",
    REFEREE4_CONFLICT_EXAMPLE: "Referee 4 Conflict Example",
    REFEREE4_HONESTY_CONCERNS: "Referee 4 Honesty Concerns",
    REFEREE4_COMPLIANCE_INCIDENTS: "Referee 4 Compliance Incidents",
    REFEREE4_LICENSE_STANDING: "Referee 4 License Standing",
    REFEREE4_PREFER_PHONE_NUMBER: "Referee 4 Prefer Phone Number",
    REFEREE4_OVERALL_RECOMMEND_SCORE: "Referee 4 Overall Recommend Score",
    REFEREE4_RECOMMEND_HIRE: "Referee 4 Recommend Hire",
    REFEREE4_CONSENT_TO_CONTACT: "Referee 4 Consent To Contact",
    REFEREE4_NOTES: "Referee 4 Notes",
    REFEREE4_GOOGLE_VERIFIED: "Referee 4 Google Verified",
    REFEREE4_GOOGLE_VERIFIED_EMAIL: "Referee 4 Google Verified Email",
    REFEREE4_GOOGLE_VERIFIED_OVERRIDE_BY: "Referee 4 Google Verified Override By",
    REFEREE4_REMINDER_24H_SENT: "Referee 4 Reminder 24h Sent",
    REFEREE4_REMINDER_48H_SENT: "Referee 4 Reminder 48h Sent",
    OUTCOME: "Outcome",
    DRIVE_FOLDER_URL: "Drive Folder URL",
    CREATED_AT: "Created At",
    SOURCE: "Source",
    STATUS: "Status",
    VERIFIED_AT: "Verified At",
    VERIFIED_BY: "Verified By",
    INITIATED_AT: "Initiated At",
    AI_OVERALL_STATUS: "AI Overall Status",
    AI_SUMMARY: "AI Summary",
    AI_RECOMMENDATION_SCORE: "AI Recommendation Score",
    AI_OVERALL_SCORE: "AI Overall Score",
    AI_CONFIDENCE_SCORE: "AI Confidence Score",
    AI_KEY_STRENGTHS: "AI Key Strengths",
    AI_AREAS_OF_CONCERN: "AI Areas Of Concern",
    AI_CONSISTENCY_NOTES: "AI Consistency Notes",
    AI_FOLLOW_UP_QUESTIONS: "AI Follow-Up Questions",
    AI_REFEREE1_TAKEAWAY: "AI Referee 1 Takeaway",
    AI_REFEREE2_TAKEAWAY: "AI Referee 2 Takeaway",
    AI_REFEREE3_TAKEAWAY: "AI Referee 3 Takeaway",
    AI_REFEREE4_TAKEAWAY: "AI Referee 4 Takeaway",
    AI_GENERATED_AT: "AI Generated At",
    REPORT_PDF: "Report PDF",
  },
  Offers: {
    OFFER_ID: "Offer ID",
    CANDIDATE: "Candidate",
    OFFERED_SALARY: "Offered Salary",
    BUDGETED_SALARY: "Budgeted Salary",
    DATE_SENT: "Date Sent",
    DEADLINE: "Deadline",
    OUTCOME: "Outcome",
    COUNTER_OFFER_AMOUNT: "Counter Offer Amount",
    FINAL_ACCEPTED_SALARY: "Final Accepted Salary",
    START_DATE: "Start Date",
    JOINED: "Joined",
    DROP_REASON: "Drop Reason",
  },
  NewEmployees: {
    EMPLOYEE_ID: "Employee ID",
    CANDIDATE: "Candidate",
    NAME: "Name",
    ROLE: "Role",
    DEPARTMENT: "Department",
    BRANCH: "Branch",
    START_DATE: "Start Date",
    EMPLOYMENT_TYPE: "Employment Type",
    CONTRACT_END: "Contract End",
    CONFIRMATION_6MO: "Confirmation 6mo",
    CONFIRMATION_6MO_AT: "Confirmation 6mo At",
    REQ_SUBMITTER_NAME: "Requisition Submitter Name",
    REQ_SUBMITTER_EMAIL: "Requisition Submitter Email",
  },
  Relievers: {
    RELIEVER_ID: "Reliever ID",
    NAME: "Name",
    ROLE: "Role",
    BRANCHES_COVERED: "Branches Covered",
    AVAILABILITY_DATES: "Availability Dates",
    STATUS: "Status",
    PHONE: "Phone",
    NOTES: "Notes",
  },
  Locums: {
    LOCUM_ID: "Locum ID",
    NAME: "Name",
    SPECIALITY: "Speciality",
    BRANCHES_COVERED: "Branches Covered",
    DAILY_RATE: "Daily Rate",
    LICENSE_NUMBER: "License Number",
    AVAILABILITY: "Availability",
    LAST_DEPLOYED: "Last Deployed",
  },
  // Monthly ground-truth headcount per branch+cadre, entered by People Ops
  // (Airtable grid for now; a BM-facing form is a later phase). Required HC
  // is deliberately NOT stored here — it's derived live from Open Roles'
  // hcApproved so it can never drift out of sync with the register.
  StaffingProjections: {
    MONTH: "Month",
    BRANCH: "Branch",
    CADRE: "Cadre",
    CURRENT_STAFFING_HC: "Current Staffing HC",
    NOTES: "Notes",
    UPDATED_BY: "Updated By",
    UPDATED_AT: "Updated At",
  },
  // Singleton config row, edited from the dashboard's Settings page — see
  // src/app/api/settings/route.ts. Always exactly one record; more
  // app-wide settings can land as additional fields on that same row later.
  AppSettings: {
    WORK_TRIAL_BOOKING_CUTOFF_DATE: "Work Trial Booking Cutoff Date",
    UPDATED_BY: "Updated By",
    UPDATED_AT: "Updated At",
  },
};

// Order matters: every multipleRecordLinks field must point at a table that
// was already created earlier in this array.
const TABLES = [
  {
    name: "Branches",
    fields: [
      { name: F.Branches.BRANCH_ID, type: "singleLineText" },
      { name: F.Branches.NAME, type: "singleLineText" },
      { name: F.Branches.CITY, type: "singleLineText" },
      { name: F.Branches.REGION, type: "singleLineText" },
      { name: F.Branches.BRANCH_MANAGER, type: "singleLineText" },
      { name: F.Branches.BM_EMAIL, type: "email" },
      { name: F.Branches.BM_PHONE, type: "phoneNumber" },
      { name: F.Branches.REGIONAL_MANAGER, type: "singleLineText" },
      { name: F.Branches.CAPACITY, type: "number", options: intOpts },
      { name: F.Branches.ACTIVE, type: "checkbox", options: checkboxOpts },
      { name: F.Branches.WORK_TRIAL_ACTIVE, type: "checkbox", options: checkboxOpts },
      { name: F.Branches.ADDRESS, type: "multilineText" },
      { name: F.Branches.MAP_PIN_URL, type: "url" },
      { name: F.Branches.EXPANSION_BRANCH, type: "checkbox", options: checkboxOpts },
      // IPS clinic vs. SO (Support Office / Telemedicine) — scopes which
      // branches show up on requisition/open-role forms for a given segment.
      { name: F.Branches.SEGMENT, type: "singleSelect", options: choices(["IPS", "SO"]) },
    ],
  },
  {
    name: "Requisitions",
    fields: [
      { name: F.Requisitions.REQ_ID, type: "singleLineText" },
      { name: F.Requisitions.TYPE, type: "singleSelect", options: choices(["SO New Role", "SO Replacement", "IPS Gap"]) },
      { name: F.Requisitions.ROLE_TITLE, type: "singleLineText" },
      { name: F.Requisitions.DEPARTMENT, type: "singleLineText" },
      { name: F.Requisitions.SEGMENT, type: "singleSelect", options: choices(["IPS", "SO"]) },
      {
        name: F.Requisitions.GAP_REASON,
        type: "singleSelect",
        options: choices(["Transfer", "Promotion", "Voluntary Resignation", "Termination", "New Addition"]),
      },
      {
        name: F.Requisitions.REASON_TYPE,
        type: "singleSelect",
        options: choices(["Resignation", "Termination", "Internal Promotion", "Retirement", "Contract End", "Other"]),
      },
      { name: F.Requisitions.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      {
        name: F.Requisitions.EMPLOYMENT_TYPE,
        type: "singleSelect",
        options: choices(["Full-time", "Part-time", "Contract", "Reliever", "Locum"]),
      },
      {
        name: F.Requisitions.LEVEL,
        type: "singleSelect",
        options: choices(["Entry", "Junior", "Mid", "Senior", "Lead", "Manager", "Senior Manager", "Head/Director"]),
      },
      { name: F.Requisitions.HEADCOUNT, type: "number", options: intOpts },
      { name: F.Requisitions.JUSTIFICATION, type: "multilineText" },
      { name: F.Requisitions.SALARY_MIN, type: "currency", options: currencyOpts },
      { name: F.Requisitions.SALARY_MAX, type: "currency", options: currencyOpts },
      { name: F.Requisitions.URGENCY, type: "singleSelect", options: choices(["Critical", "High", "Medium", "Low"]) },
      { name: F.Requisitions.JD_ATTACHED, type: "checkbox", options: checkboxOpts },
      { name: F.Requisitions.JD_URL, type: "url" },
      {
        name: F.Requisitions.STATUS,
        type: "singleSelect",
        options: choices(["Pending Approval", "Approved", "Rejected", "Converted to Open Role"]),
      },
      { name: F.Requisitions.APPROVER_CHAIN, type: "multilineText" },
      { name: F.Requisitions.CURRENT_APPROVER_INDEX, type: "number", options: intOpts },
      { name: F.Requisitions.SUBMITTED_BY, type: "singleLineText" },
      { name: F.Requisitions.SUBMITTED_AT, type: "date", options: dateOpts },
      { name: F.Requisitions.EXPECTED_START_DATE, type: "date", options: dateOpts },
      { name: F.Requisitions.CONTEXT, type: "multilineText" },
      { name: F.Requisitions.SUBMITTER_NAME, type: "singleLineText" },
      { name: F.Requisitions.SUBMITTER_EMAIL, type: "email" },
      { name: F.Requisitions.SUBMITTER_ROLE, type: "singleLineText" },
      { name: F.Requisitions.SOURCE, type: "singleSelect", options: choices(["internal", "public-link"]) },
      { name: F.Requisitions.BUDGET_EVALUATION_CONFIRMED, type: "checkbox", options: checkboxOpts },
    ],
  },
  {
    name: "Open Roles",
    fields: [
      { name: F.OpenRoles.ROLE_ID, type: "singleLineText" },
      { name: F.OpenRoles.TITLE, type: "singleLineText" },
      { name: F.OpenRoles.SEGMENT, type: "singleSelect", options: choices(["IPS", "SO"]) },
      { name: F.OpenRoles.DEPARTMENT, type: "singleLineText" },
      { name: F.OpenRoles.LOCATION, type: "singleLineText" },
      { name: F.OpenRoles.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      { name: F.OpenRoles.PRIORITY, type: "singleSelect", options: choices(["Critical", "High", "Medium", "Low"]) },
      { name: F.OpenRoles.STATUS, type: "singleSelect", options: choices(["Open", "Allocated", "Filled", "On Hold", "Cancelled"]) },
      { name: F.OpenRoles.HC_APPROVED, type: "number", options: intOpts },
      { name: F.OpenRoles.HC_FILLED, type: "number", options: intOpts },
      { name: F.OpenRoles.RECRUITER, type: "singleLineText" },
      { name: F.OpenRoles.HIRING_MANAGER, type: "singleLineText" },
      { name: F.OpenRoles.HIRING_MANAGER_EMAIL, type: "email" },
      { name: F.OpenRoles.DATE_POSTED, type: "date", options: dateOpts },
      { name: F.OpenRoles.DATE_CLOSED, type: "date", options: dateOpts },
      {
        name: F.OpenRoles.EMPLOYMENT_TYPE,
        type: "singleSelect",
        options: choices(["Full-time", "Part-time", "Contract", "Reliever", "Locum"]),
      },
      { name: F.OpenRoles.NOTES, type: "multilineText" },
      { name: F.OpenRoles.INTERNAL_FILL, type: "checkbox", options: checkboxOpts },
      { name: F.OpenRoles.INTERNAL_FILL_NAME, type: "singleLineText" },
      { name: F.OpenRoles.REQUISITION, type: "multipleRecordLinks", linkedTable: "Requisitions" },
      { name: F.OpenRoles.REQ_SUBMITTER_NAME, type: "singleLineText" },
      { name: F.OpenRoles.REQ_SUBMITTER_EMAIL, type: "email" },
      { name: F.OpenRoles.REPLACEMENT_REQUISITION, type: "multipleRecordLinks", linkedTable: "Requisitions" },
      { name: F.OpenRoles.CADRE, type: "singleSelect", options: choices(CADRES) },
    ],
  },
  {
    name: "Candidates",
    fields: [
      { name: F.Candidates.CAND_ID, type: "singleLineText" },
      { name: F.Candidates.NAME, type: "singleLineText" },
      { name: F.Candidates.PHONE, type: "phoneNumber" },
      { name: F.Candidates.EMAIL, type: "email" },
      { name: F.Candidates.ROLE, type: "multipleRecordLinks", linkedTable: "Open Roles" },
      {
        name: F.Candidates.STAGE,
        type: "singleSelect",
        options: choices([
          "First Interview", "Second Interview", "Panel Interview", "Work Trial",
          "Reference Check", "Offer", "Hired", "Backup Pool", "Rejected", "Withdrawn",
        ]),
      },
      { name: F.Candidates.SOURCE, type: "singleLineText" },
      { name: F.Candidates.GENDER, type: "singleSelect", options: choices(["Male", "Female"]) },
      {
        name: F.Candidates.EMPLOYMENT_TYPE,
        type: "singleSelect",
        options: choices(["Full-time", "Part-time", "Contract", "Reliever", "Locum"]),
      },
      { name: F.Candidates.REFEREE1_NAME, type: "singleLineText" },
      { name: F.Candidates.REFEREE1_EMAIL, type: "email" },
      { name: F.Candidates.REFEREE1_PHONE, type: "phoneNumber" },
      { name: F.Candidates.REFEREE2_NAME, type: "singleLineText" },
      { name: F.Candidates.REFEREE2_EMAIL, type: "email" },
      { name: F.Candidates.REFEREE2_PHONE, type: "phoneNumber" },
      {
        name: F.Candidates.WORK_TRIAL_STATUS,
        type: "singleSelect",
        options: choices(["Scheduled", "Awaiting Arrival", "Awaiting Score", "Complete"]),
      },
      { name: F.Candidates.REF_CHECK_STATUS, type: "singleLineText" },
      {
        name: F.Candidates.OFFER_STATUS,
        type: "singleSelect",
        options: choices(["Pending", "Accepted", "Declined", "Negotiating", "Withdrawn"]),
      },
      { name: F.Candidates.JOINED, type: "singleSelect", options: choices(["Pending", "Joined", "Did Not Join"]) },
      { name: F.Candidates.STAGE_ENTERED_AT, type: "date", options: dateOpts },
      { name: F.Candidates.CREATED_AT, type: "date", options: dateOpts },
    ],
  },
  {
    name: "Interviews",
    fields: [
      { name: F.Interviews.SCHED_ID, type: "singleLineText" },
      { name: F.Interviews.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.Interviews.ROLE, type: "multipleRecordLinks", linkedTable: "Open Roles" },
      { name: F.Interviews.DATE, type: "date", options: dateOpts },
      { name: F.Interviews.TIME, type: "singleLineText" },
      { name: F.Interviews.WEEK_LABEL, type: "singleLineText" },
      { name: F.Interviews.MONTH, type: "singleLineText" },
      { name: F.Interviews.STAGE, type: "singleSelect", options: choices(["First Interview", "Second Interview", "Panel Interview"]) },
      { name: F.Interviews.TYPE, type: "singleSelect", options: choices(["In-person", "Google Meet", "Phone", "WhatsApp"]) },
      { name: F.Interviews.LOCATION, type: "singleLineText" },
      { name: F.Interviews.INTERVIEWERS, type: "multilineText" },
      { name: F.Interviews.CONFIRMED, type: "checkbox", options: checkboxOpts },
      { name: F.Interviews.REMINDER_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.Interviews.ATTENDANCE, type: "singleSelect", options: choices(["Attended", "No-show", "Pending"]) },
      { name: F.Interviews.OUTCOME, type: "singleSelect", options: choices(["Pass", "Fail", "Pending"]) },
      { name: F.Interviews.NOTES, type: "multilineText" },
    ],
  },
  {
    name: "Work Trials",
    fields: [
      { name: F.WorkTrials.WT_ID, type: "singleLineText" },
      { name: F.WorkTrials.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.WorkTrials.ROLE, type: "multipleRecordLinks", linkedTable: "Open Roles" },
      { name: F.WorkTrials.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      { name: F.WorkTrials.DATE, type: "date", options: dateOpts },
      { name: F.WorkTrials.SUPERVISOR, type: "singleLineText" },
      { name: F.WorkTrials.CREATED_AT, type: "date", options: dateOpts },
      { name: F.WorkTrials.ARRIVAL_MARKED, type: "singleSelect", options: choices(["Arrived", "Not Arrived", "Pending"]) },
      { name: F.WorkTrials.SCORE_TECHNICAL, type: "number", options: scoreOpts },
      { name: F.WorkTrials.SCORE_PATIENT, type: "number", options: scoreOpts },
      { name: F.WorkTrials.SCORE_SAFETY, type: "number", options: scoreOpts },
      { name: F.WorkTrials.SCORE_CULTURE, type: "number", options: scoreOpts },
      { name: F.WorkTrials.TOTAL, type: "number", options: scoreOpts },
      { name: F.WorkTrials.PASS_FAIL, type: "singleSelect", options: choices(["Pass", "Fail", "Pending"]) },
      { name: F.WorkTrials.FORM_SUBMITTED_AT, type: "date", options: dateOpts },
      { name: F.WorkTrials.SUBMITTED_BY_ROLE, type: "singleLineText" },
      { name: F.WorkTrials.BM_APPROVED_AT, type: "date", options: dateOpts },
      { name: F.WorkTrials.BM_SCORING_LINK, type: "url" },
      { name: F.WorkTrials.REMINDER_12H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.WorkTrials.ESCALATION_24H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.WorkTrials.COMMENT_CULTURE, type: "multilineText" },
      { name: F.WorkTrials.COMMENT_PATIENT, type: "multilineText" },
      { name: F.WorkTrials.COMMENT_TECHNICAL, type: "multilineText" },
      { name: F.WorkTrials.STRENGTHS, type: "multilineText" },
      { name: F.WorkTrials.AREAS_OF_DEVELOPMENT, type: "multilineText" },
      { name: F.WorkTrials.OVERALL_RECOMMENDATION, type: "multilineText" },
      { name: F.WorkTrials.SUBMISSION_METHOD, type: "singleSelect", options: choices(["Online", "Uploaded"]) },
      { name: F.WorkTrials.UPLOADED_FORM, type: "multipleAttachments" },
    ],
  },
  {
    name: "Reference Checks",
    fields: [
      { name: F.ReferenceChecks.REF_ID, type: "singleLineText" },
      { name: F.ReferenceChecks.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.ReferenceChecks.REFEREE1_NAME, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE1_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE1_PHONE, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE1_EMAIL_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_SMS_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_RESPONDED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_RESPONDED_AT, type: "date", options: dateOpts },
      {
        name: F.ReferenceChecks.REFEREE1_RELATIONSHIP,
        type: "singleSelect",
        options: choices(["Direct manager", "Senior colleague", "Peer / colleague", "Client or patient", "Other professional"]),
      },
      { name: F.ReferenceChecks.REFEREE1_DIRECTLY_SUPERVISED, type: "checkbox", options: checkboxOpts },
      {
        name: F.ReferenceChecks.REFEREE1_REPORTING_RELATIONSHIP,
        type: "singleSelect",
        options: choices(REPORTING_RELATIONSHIP_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE1_ORGANIZATION, type: "singleLineText" },
      {
        name: F.ReferenceChecks.REFEREE1_DURATION_KNOWN,
        type: "singleSelect",
        options: choices(["Less than 1 year", "1-2 years", "2-5 years", "5+ years"]),
      },
      {
        name: F.ReferenceChecks.REFEREE1_INTERACTION_FREQUENCY,
        type: "singleSelect",
        options: choices(INTERACTION_FREQUENCY_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE1_JOB_TITLE_RECALLED, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE1_EMPLOYMENT_FROM, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REFEREE1_EMPLOYMENT_TO, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REFEREE1_STILL_EMPLOYED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_MAIN_RESPONSIBILITIES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_REPORTED_TO, type: "singleLineText" },
      {
        name: F.ReferenceChecks.REFEREE1_LEAVING_REASON,
        type: "singleSelect",
        options: choices(LEAVING_REASON_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE1_TECH_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE1_RELIABILITY_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE1_EXECUTION_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE1_EXECUTION_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_TEAMWORK_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE1_TEAMWORK_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_COMMUNICATION_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE1_COMMUNICATION_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_PROBLEM_SOLVING_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE1_ADAPTABILITY_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE1_WOULD_REHIRE,
        type: "singleSelect",
        // Older sets kept for history (never removed from a live field — see
        // SETUP.md); the current redesigned /referee form only ever offers/
        // writes the first 3 (Yes / With reservations / No).
        options: choices(WOULD_REHIRE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE1_WOULD_REHIRE_EXPLANATION, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_STRENGTH_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_DEVELOPMENT_AREAS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_STRENGTHS_AND_DEVELOPMENT, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_TOP_STRENGTHS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_COACHING_AREA, type: "multilineText" },
      {
        name: F.ReferenceChecks.REFEREE1_FEEDBACK_RESPONSE,
        type: "singleSelect",
        options: choices(FEEDBACK_RESPONSE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE1_CONFLICT_EXAMPLE, type: "multilineText" },
      {
        name: F.ReferenceChecks.REFEREE1_HONESTY_CONCERNS,
        type: "singleSelect",
        options: choices(["No concerns", "Some concerns", "Prefer to discuss by phone"]),
      },
      {
        name: F.ReferenceChecks.REFEREE1_COMPLIANCE_INCIDENTS,
        type: "singleSelect",
        options: choices(["None that I know of", "Yes", "Prefer to discuss by phone"]),
      },
      {
        name: F.ReferenceChecks.REFEREE1_LICENSE_STANDING,
        type: "singleSelect",
        options: choices(["Yes", "No", "N/A", "Not sure"]),
      },
      { name: F.ReferenceChecks.REFEREE1_PREFER_PHONE_NUMBER, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE1_OVERALL_RECOMMEND_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE1_RECOMMEND_HIRE,
        type: "singleSelect",
        options: choices(RECOMMEND_HIRE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE1_CONSENT_TO_CONTACT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_NOTES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE1_GOOGLE_VERIFIED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_GOOGLE_VERIFIED_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE1_GOOGLE_VERIFIED_OVERRIDE_BY, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE1_REMINDER_24H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE1_REMINDER_48H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_NAME, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE2_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE2_PHONE, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE2_EMAIL_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_SMS_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_RESPONDED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_RESPONDED_AT, type: "date", options: dateOpts },
      {
        name: F.ReferenceChecks.REFEREE2_RELATIONSHIP,
        type: "singleSelect",
        options: choices(["Direct manager", "Senior colleague", "Peer / colleague", "Client or patient", "Other professional"]),
      },
      { name: F.ReferenceChecks.REFEREE2_DIRECTLY_SUPERVISED, type: "checkbox", options: checkboxOpts },
      {
        name: F.ReferenceChecks.REFEREE2_REPORTING_RELATIONSHIP,
        type: "singleSelect",
        options: choices(REPORTING_RELATIONSHIP_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE2_ORGANIZATION, type: "singleLineText" },
      {
        name: F.ReferenceChecks.REFEREE2_DURATION_KNOWN,
        type: "singleSelect",
        options: choices(["Less than 1 year", "1-2 years", "2-5 years", "5+ years"]),
      },
      {
        name: F.ReferenceChecks.REFEREE2_INTERACTION_FREQUENCY,
        type: "singleSelect",
        options: choices(INTERACTION_FREQUENCY_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE2_JOB_TITLE_RECALLED, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE2_EMPLOYMENT_FROM, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REFEREE2_EMPLOYMENT_TO, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REFEREE2_STILL_EMPLOYED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_MAIN_RESPONSIBILITIES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_REPORTED_TO, type: "singleLineText" },
      {
        name: F.ReferenceChecks.REFEREE2_LEAVING_REASON,
        type: "singleSelect",
        options: choices(LEAVING_REASON_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE2_TECH_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE2_RELIABILITY_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE2_EXECUTION_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE2_EXECUTION_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_TEAMWORK_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE2_TEAMWORK_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_COMMUNICATION_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE2_COMMUNICATION_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_PROBLEM_SOLVING_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE2_ADAPTABILITY_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE2_WOULD_REHIRE,
        type: "singleSelect",
        options: choices(WOULD_REHIRE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE2_WOULD_REHIRE_EXPLANATION, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_STRENGTH_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_DEVELOPMENT_AREAS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_STRENGTHS_AND_DEVELOPMENT, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_TOP_STRENGTHS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_COACHING_AREA, type: "multilineText" },
      {
        name: F.ReferenceChecks.REFEREE2_FEEDBACK_RESPONSE,
        type: "singleSelect",
        options: choices(FEEDBACK_RESPONSE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE2_CONFLICT_EXAMPLE, type: "multilineText" },
      {
        name: F.ReferenceChecks.REFEREE2_HONESTY_CONCERNS,
        type: "singleSelect",
        options: choices(["No concerns", "Some concerns", "Prefer to discuss by phone"]),
      },
      {
        name: F.ReferenceChecks.REFEREE2_COMPLIANCE_INCIDENTS,
        type: "singleSelect",
        options: choices(["None that I know of", "Yes", "Prefer to discuss by phone"]),
      },
      {
        name: F.ReferenceChecks.REFEREE2_LICENSE_STANDING,
        type: "singleSelect",
        options: choices(["Yes", "No", "N/A", "Not sure"]),
      },
      { name: F.ReferenceChecks.REFEREE2_PREFER_PHONE_NUMBER, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE2_OVERALL_RECOMMEND_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE2_RECOMMEND_HIRE,
        type: "singleSelect",
        options: choices(RECOMMEND_HIRE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE2_CONSENT_TO_CONTACT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_NOTES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE2_GOOGLE_VERIFIED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_GOOGLE_VERIFIED_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE2_GOOGLE_VERIFIED_OVERRIDE_BY, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE2_REMINDER_24H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE2_REMINDER_48H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE3_NAME, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE3_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE3_PHONE, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE3_EMAIL_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE3_SMS_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE3_RESPONDED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE3_RESPONDED_AT, type: "date", options: dateOpts },
      {
        name: F.ReferenceChecks.REFEREE3_RELATIONSHIP,
        type: "singleSelect",
        options: choices(["Direct manager", "Senior colleague", "Peer / colleague", "Client or patient", "Other professional"]),
      },
      { name: F.ReferenceChecks.REFEREE3_DIRECTLY_SUPERVISED, type: "checkbox", options: checkboxOpts },
      {
        name: F.ReferenceChecks.REFEREE3_REPORTING_RELATIONSHIP,
        type: "singleSelect",
        options: choices(REPORTING_RELATIONSHIP_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE3_ORGANIZATION, type: "singleLineText" },
      {
        name: F.ReferenceChecks.REFEREE3_DURATION_KNOWN,
        type: "singleSelect",
        options: choices(["Less than 1 year", "1-2 years", "2-5 years", "5+ years"]),
      },
      {
        name: F.ReferenceChecks.REFEREE3_INTERACTION_FREQUENCY,
        type: "singleSelect",
        options: choices(INTERACTION_FREQUENCY_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE3_JOB_TITLE_RECALLED, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE3_EMPLOYMENT_FROM, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REFEREE3_EMPLOYMENT_TO, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REFEREE3_STILL_EMPLOYED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE3_MAIN_RESPONSIBILITIES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_REPORTED_TO, type: "singleLineText" },
      {
        name: F.ReferenceChecks.REFEREE3_LEAVING_REASON,
        type: "singleSelect",
        options: choices(LEAVING_REASON_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE3_TECH_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE3_RELIABILITY_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE3_EXECUTION_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE3_EXECUTION_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_TEAMWORK_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE3_TEAMWORK_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_COMMUNICATION_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE3_COMMUNICATION_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_PROBLEM_SOLVING_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE3_ADAPTABILITY_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE3_WOULD_REHIRE,
        type: "singleSelect",
        options: choices(WOULD_REHIRE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE3_WOULD_REHIRE_EXPLANATION, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_STRENGTH_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_DEVELOPMENT_AREAS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_STRENGTHS_AND_DEVELOPMENT, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_TOP_STRENGTHS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_COACHING_AREA, type: "multilineText" },
      {
        name: F.ReferenceChecks.REFEREE3_FEEDBACK_RESPONSE,
        type: "singleSelect",
        options: choices(FEEDBACK_RESPONSE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE3_CONFLICT_EXAMPLE, type: "multilineText" },
      {
        name: F.ReferenceChecks.REFEREE3_HONESTY_CONCERNS,
        type: "singleSelect",
        options: choices(["No concerns", "Some concerns", "Prefer to discuss by phone"]),
      },
      {
        name: F.ReferenceChecks.REFEREE3_COMPLIANCE_INCIDENTS,
        type: "singleSelect",
        options: choices(["None that I know of", "Yes", "Prefer to discuss by phone"]),
      },
      {
        name: F.ReferenceChecks.REFEREE3_LICENSE_STANDING,
        type: "singleSelect",
        options: choices(["Yes", "No", "N/A", "Not sure"]),
      },
      { name: F.ReferenceChecks.REFEREE3_PREFER_PHONE_NUMBER, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE3_OVERALL_RECOMMEND_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE3_RECOMMEND_HIRE,
        type: "singleSelect",
        options: choices(RECOMMEND_HIRE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE3_CONSENT_TO_CONTACT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE3_NOTES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE3_GOOGLE_VERIFIED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE3_GOOGLE_VERIFIED_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE3_GOOGLE_VERIFIED_OVERRIDE_BY, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE3_REMINDER_24H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE3_REMINDER_48H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE4_NAME, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE4_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE4_PHONE, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE4_EMAIL_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE4_SMS_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE4_RESPONDED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE4_RESPONDED_AT, type: "date", options: dateOpts },
      {
        name: F.ReferenceChecks.REFEREE4_RELATIONSHIP,
        type: "singleSelect",
        options: choices(["Direct manager", "Senior colleague", "Peer / colleague", "Client or patient", "Other professional"]),
      },
      { name: F.ReferenceChecks.REFEREE4_DIRECTLY_SUPERVISED, type: "checkbox", options: checkboxOpts },
      {
        name: F.ReferenceChecks.REFEREE4_REPORTING_RELATIONSHIP,
        type: "singleSelect",
        options: choices(REPORTING_RELATIONSHIP_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE4_ORGANIZATION, type: "singleLineText" },
      {
        name: F.ReferenceChecks.REFEREE4_DURATION_KNOWN,
        type: "singleSelect",
        options: choices(["Less than 1 year", "1-2 years", "2-5 years", "5+ years"]),
      },
      {
        name: F.ReferenceChecks.REFEREE4_INTERACTION_FREQUENCY,
        type: "singleSelect",
        options: choices(INTERACTION_FREQUENCY_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE4_JOB_TITLE_RECALLED, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE4_EMPLOYMENT_FROM, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REFEREE4_EMPLOYMENT_TO, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REFEREE4_STILL_EMPLOYED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE4_MAIN_RESPONSIBILITIES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_REPORTED_TO, type: "singleLineText" },
      {
        name: F.ReferenceChecks.REFEREE4_LEAVING_REASON,
        type: "singleSelect",
        options: choices(LEAVING_REASON_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE4_TECH_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE4_RELIABILITY_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE4_EXECUTION_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE4_EXECUTION_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_TEAMWORK_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE4_TEAMWORK_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_COMMUNICATION_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE4_COMMUNICATION_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_PROBLEM_SOLVING_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.REFEREE4_ADAPTABILITY_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE4_WOULD_REHIRE,
        type: "singleSelect",
        options: choices(WOULD_REHIRE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE4_WOULD_REHIRE_EXPLANATION, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_STRENGTH_EXAMPLE, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_DEVELOPMENT_AREAS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_STRENGTHS_AND_DEVELOPMENT, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_TOP_STRENGTHS, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_COACHING_AREA, type: "multilineText" },
      {
        name: F.ReferenceChecks.REFEREE4_FEEDBACK_RESPONSE,
        type: "singleSelect",
        options: choices(FEEDBACK_RESPONSE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE4_CONFLICT_EXAMPLE, type: "multilineText" },
      {
        name: F.ReferenceChecks.REFEREE4_HONESTY_CONCERNS,
        type: "singleSelect",
        options: choices(["No concerns", "Some concerns", "Prefer to discuss by phone"]),
      },
      {
        name: F.ReferenceChecks.REFEREE4_COMPLIANCE_INCIDENTS,
        type: "singleSelect",
        options: choices(["None that I know of", "Yes", "Prefer to discuss by phone"]),
      },
      {
        name: F.ReferenceChecks.REFEREE4_LICENSE_STANDING,
        type: "singleSelect",
        options: choices(["Yes", "No", "N/A", "Not sure"]),
      },
      { name: F.ReferenceChecks.REFEREE4_PREFER_PHONE_NUMBER, type: "phoneNumber" },
      { name: F.ReferenceChecks.REFEREE4_OVERALL_RECOMMEND_SCORE, type: "number", options: intOpts },
      {
        name: F.ReferenceChecks.REFEREE4_RECOMMEND_HIRE,
        type: "singleSelect",
        options: choices(RECOMMEND_HIRE_OPTIONS),
      },
      { name: F.ReferenceChecks.REFEREE4_CONSENT_TO_CONTACT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE4_NOTES, type: "multilineText" },
      { name: F.ReferenceChecks.REFEREE4_GOOGLE_VERIFIED, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE4_GOOGLE_VERIFIED_EMAIL, type: "email" },
      { name: F.ReferenceChecks.REFEREE4_GOOGLE_VERIFIED_OVERRIDE_BY, type: "singleLineText" },
      { name: F.ReferenceChecks.REFEREE4_REMINDER_24H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.REFEREE4_REMINDER_48H_SENT, type: "checkbox", options: checkboxOpts },
      { name: F.ReferenceChecks.OUTCOME, type: "singleSelect", options: choices(["Pending", "Positive", "Negative", "Mixed"]) },
      { name: F.ReferenceChecks.DRIVE_FOLDER_URL, type: "url" },
      { name: F.ReferenceChecks.CREATED_AT, type: "date", options: dateOpts },
      {
        name: F.ReferenceChecks.SOURCE,
        type: "singleSelect",
        options: choices(["TA Added", "Candidate Submitted"]),
      },
      {
        name: F.ReferenceChecks.STATUS,
        type: "singleSelect",
        options: choices(["Awaiting Verification", "Awaiting Responses", "1 Referee In", "Ready for Offer"]),
      },
      { name: F.ReferenceChecks.VERIFIED_AT, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.VERIFIED_BY, type: "singleLineText" },
      { name: F.ReferenceChecks.INITIATED_AT, type: "date", options: dateOpts },
      // AI "intelligence and insights layer" (src/lib/ai/reference-check-summary.ts)
      // — persisted here (not just embedded in the PDF) so it shows on the
      // dashboard card and flows into Penny's chat context. Array-shaped
      // fields (strengths, concerns, follow-ups) are stored as newline-joined
      // plain text rather than JSON, matching this table's existing
      // preference for human-readable text fields over serialized blobs.
      {
        name: F.ReferenceChecks.AI_OVERALL_STATUS,
        type: "singleSelect",
        options: choices(["Strong Recommend", "Recommend", "Recommend with Reservations", "Do Not Recommend", "Insufficient Data"]),
      },
      { name: F.ReferenceChecks.AI_SUMMARY, type: "multilineText" },
      { name: F.ReferenceChecks.AI_RECOMMENDATION_SCORE, type: "number", options: scoreOpts },
      { name: F.ReferenceChecks.AI_OVERALL_SCORE, type: "number", options: scoreOpts },
      { name: F.ReferenceChecks.AI_CONFIDENCE_SCORE, type: "number", options: intOpts },
      { name: F.ReferenceChecks.AI_KEY_STRENGTHS, type: "multilineText" },
      { name: F.ReferenceChecks.AI_AREAS_OF_CONCERN, type: "multilineText" },
      { name: F.ReferenceChecks.AI_CONSISTENCY_NOTES, type: "multilineText" },
      { name: F.ReferenceChecks.AI_FOLLOW_UP_QUESTIONS, type: "multilineText" },
      { name: F.ReferenceChecks.AI_REFEREE1_TAKEAWAY, type: "multilineText" },
      { name: F.ReferenceChecks.AI_REFEREE2_TAKEAWAY, type: "multilineText" },
      { name: F.ReferenceChecks.AI_REFEREE3_TAKEAWAY, type: "multilineText" },
      { name: F.ReferenceChecks.AI_REFEREE4_TAKEAWAY, type: "multilineText" },
      { name: F.ReferenceChecks.AI_GENERATED_AT, type: "date", options: dateOpts },
      { name: F.ReferenceChecks.REPORT_PDF, type: "multipleAttachments" },
    ],
  },
  {
    name: "Offers",
    fields: [
      { name: F.Offers.OFFER_ID, type: "singleLineText" },
      { name: F.Offers.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.Offers.OFFERED_SALARY, type: "currency", options: currencyOpts },
      { name: F.Offers.BUDGETED_SALARY, type: "currency", options: currencyOpts },
      { name: F.Offers.DATE_SENT, type: "date", options: dateOpts },
      { name: F.Offers.DEADLINE, type: "date", options: dateOpts },
      { name: F.Offers.OUTCOME, type: "singleSelect", options: choices(["Pending", "Accepted", "Declined", "Negotiating", "Withdrawn"]) },
      { name: F.Offers.COUNTER_OFFER_AMOUNT, type: "currency", options: currencyOpts },
      { name: F.Offers.FINAL_ACCEPTED_SALARY, type: "currency", options: currencyOpts },
      { name: F.Offers.START_DATE, type: "date", options: dateOpts },
      { name: F.Offers.JOINED, type: "singleSelect", options: choices(["Pending", "Joined", "Did Not Join"]) },
      { name: F.Offers.DROP_REASON, type: "multilineText" },
    ],
  },
  {
    name: "New Employees",
    fields: [
      { name: F.NewEmployees.EMPLOYEE_ID, type: "singleLineText" },
      { name: F.NewEmployees.CANDIDATE, type: "multipleRecordLinks", linkedTable: "Candidates" },
      { name: F.NewEmployees.NAME, type: "singleLineText" },
      { name: F.NewEmployees.ROLE, type: "singleLineText" },
      { name: F.NewEmployees.DEPARTMENT, type: "singleLineText" },
      { name: F.NewEmployees.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      { name: F.NewEmployees.START_DATE, type: "date", options: dateOpts },
      {
        name: F.NewEmployees.EMPLOYMENT_TYPE,
        type: "singleSelect",
        options: choices(["Full-time", "Part-time", "Contract", "Reliever", "Locum"]),
      },
      { name: F.NewEmployees.CONTRACT_END, type: "date", options: dateOpts },
      {
        name: F.NewEmployees.CONFIRMATION_6MO,
        type: "singleSelect",
        options: choices(["Pending", "Confirmed", "Not Confirmed"]),
      },
      { name: F.NewEmployees.CONFIRMATION_6MO_AT, type: "date", options: dateOpts },
      { name: F.NewEmployees.REQ_SUBMITTER_NAME, type: "singleLineText" },
      { name: F.NewEmployees.REQ_SUBMITTER_EMAIL, type: "email" },
    ],
  },
  {
    name: "Relievers",
    fields: [
      { name: F.Relievers.RELIEVER_ID, type: "singleLineText" },
      { name: F.Relievers.NAME, type: "singleLineText" },
      { name: F.Relievers.ROLE, type: "singleSelect", options: choices(RELIEVER_CADRES) },
      { name: F.Relievers.BRANCHES_COVERED, type: "multipleSelects", options: choices(ALL_BRANCHES) },
      { name: F.Relievers.AVAILABILITY_DATES, type: "singleLineText" },
      { name: F.Relievers.STATUS, type: "singleSelect", options: choices(["Active", "Inactive"]) },
      { name: F.Relievers.PHONE, type: "phoneNumber" },
      { name: F.Relievers.NOTES, type: "multilineText" },
    ],
  },
  {
    name: "Locums",
    fields: [
      { name: F.Locums.LOCUM_ID, type: "singleLineText" },
      { name: F.Locums.NAME, type: "singleLineText" },
      {
        name: F.Locums.SPECIALITY,
        type: "singleSelect",
        options: choices(["General Practice", "Dental", "Pharmacy", "Sonography"]),
      },
      { name: F.Locums.BRANCHES_COVERED, type: "multipleSelects", options: choices(COVERAGE_ZONES) },
      { name: F.Locums.DAILY_RATE, type: "currency", options: currencyOpts },
      { name: F.Locums.LICENSE_NUMBER, type: "singleLineText" },
      { name: F.Locums.AVAILABILITY, type: "singleLineText" },
      { name: F.Locums.LAST_DEPLOYED, type: "date", options: dateOpts },
    ],
  },
  {
    name: "Staffing Projections",
    fields: [
      { name: F.StaffingProjections.MONTH, type: "date", options: dateOpts },
      { name: F.StaffingProjections.BRANCH, type: "multipleRecordLinks", linkedTable: "Branches" },
      { name: F.StaffingProjections.CADRE, type: "singleSelect", options: choices(CADRES) },
      { name: F.StaffingProjections.CURRENT_STAFFING_HC, type: "number", options: decimalOpts },
      { name: F.StaffingProjections.NOTES, type: "multilineText" },
      { name: F.StaffingProjections.UPDATED_BY, type: "singleLineText" },
      { name: F.StaffingProjections.UPDATED_AT, type: "date", options: dateOpts },
    ],
  },
  {
    name: "App Settings",
    fields: [
      // Exclusive: no new work-trial date on or after this may be booked
      // (candidate self-serve /work-trial-request). Blank = no cutoff, falls
      // back to the default rolling window (see src/lib/work-trial-timing.ts).
      { name: F.AppSettings.WORK_TRIAL_BOOKING_CUTOFF_DATE, type: "date", options: dateOpts },
      { name: F.AppSettings.UPDATED_BY, type: "singleLineText" },
      { name: F.AppSettings.UPDATED_AT, type: "date", options: dateOpts },
    ],
  },
];

module.exports = { TABLES, F };
